### ISSUE TITLE
Change currency

### ISSUE THREAD

**Issue by xav12** [smartstoreag/SmartStoreNET#1004]
I try to add currency and complete the attribute like rate.
But the price is not appear.
Pls Help me
![capture3](https://cloud.githubusercontent.com/assets/20593238/17053871/463d2dca-502e-11e6-9ea9-35152d16ac98.PNG)

**Comment by mgesing** [comment]
This could help
http://community.smartstore.com/index.php?/topic/47906-currency-specific-code-not-included-for-my-country/
