### ISSUE TITLE
Bug on file src\Libraries\SmartStore.Services\Media\ImageCache.cs

### ISSUE THREAD

**Issue by ronikurnia1** [smartstoreag/SmartStoreNET#1005]
Got an error when removing/deleting an image (e.g. Logo image) due to the the **BuildPath** function on src\Libraries\SmartStore.Services\Media\ImageCache.cs not properly work:

Before:

		private string BuildPath(string imagePath)
		{
			if (imagePath.IsEmpty())
				return null;
			return _thumbsRootDir + imagePath;
		}

After I fix:

		private string BuildPath(string imagePath)
		{
			if (imagePath.IsEmpty())
				return null;
			if (imagePath.Contains(_thumbsRootDir.Replace("/", "\\")))
				return imagePath;
			return _thumbsRootDir + imagePath;
		}

**Comment by mgesing** [comment]
Thank you for reporting! The bug has already been fixed in the feature/media-storage branch.
