### ISSUE TITLE
Cannot start debugging SmartStoreNET because of bundle issue

### ISSUE THREAD

**Issue by qmenq07** [smartstoreag/SmartStoreNET#1006]
Hello team,

Please help to take a look at my issue. I'm using version 3.0.

![image](https://cloud.githubusercontent.com/assets/5336332/17075597/55e9b970-50c2-11e6-85d0-d953283a27a9.png)

Thanks,
Quan Tran

**Comment by qmenq07** [comment]
My local info:

IIS 7.5
Visual studio 2015 community

Thank you!

**Comment by mgesing** [comment]
Open web.config and switch jsEngine to "V8JsEngine".

**Comment by qmenq07** [comment]
Dear @mgesing ,

it works well now, thank you so much. Could you please show me why i have to use "V8JsEngine" as a short brief?

Regards,
Quan Tran

**Comment by mgesing** [comment]
Unfortunately, I do not know the exact reason. Sometimes users reports problems with the IE javascript engine but when they switch it, all works well.
