### ISSUE TITLE
Throwing exceptions in ProductBundleDataConverter.

### ISSUE THREAD

**Issue by KostaVlev** [smartstoreag/SmartStoreNET#1018]
In `SmartStore.Core.ProductBundleDataConverter.cs` have you considered using the `CanConvertFrom()` inside the `ConvertFrom()` to check if the type is convertible and if not to thrown  exception. Also the `result` of the conversion can be checked for `null` instead of calling the `base.ConvertFrom().` 
This way exceptions will be cough earlier.

**Comment by muratcakir** [comment]
Running into an exception when passed (xml)-value is malformed is on purpose here
