### ISSUE TITLE
AdditionalCharge validation.

### ISSUE THREAD

**Issue by KostaVlev** [smartstoreag/SmartStoreNET#1020]
The `AdditionalCharge` property of `SmartStore.Core.Domain.Catalog.ProductBundleItemData` is not validated and its possible to be set as negative number.

**Comment by mgesing** [comment]
ProductBundleItemData.AdditionalCharge is a cargo data field for dynamic price calculation. It contains the sum of price adjustments of selected attributes and these adjustments explicitly allow negative values.
