### ISSUE TITLE
SmartStore /Admin returns 404 Error 

### ISSUE THREAD

**Issue by rezaya2938** [smartstoreag/SmartStoreNET#1045]
Hi. I just downloaded the source code. when I run it on VS2015, After Installation, the admin panel returns a 404 error.
when I try to **load locallhost:0000/admin** , returns 404 error
how can I fix it?
tnx in advance

![GitHub Logo](http://s9.picofile.com/file/8272791784/smart.PNG)

**Comment by mgesing** [comment]
Do not compile build configuration "PluginDev". Choose "Debug" or "Release".

**Comment by rezaya2938** [comment]
All configurations are set to "Debug". its not working. I tried version 2.6 . doesn't work either.
but when I create website in IIS, works. just when I run on VS , not working!

**Comment by mgesing** [comment]
Open App_Data/InstalledPlugins.txt and check each plugin name if it exists in Plugin folder. Remove plugin names that does not exist in Plugin folder. Save InstalledPlugins.txt and restart application.

**Comment by rezaya2938** [comment]
there is no "InstalledPlugins.txt" anywhere in solution!

**Comment by mgesing** [comment]
It's not part of the solution. The file is dynamically created by installation. It it doesn't exist then please re-install by deleting App_Data/Setting.txt.

**Comment by liuhaifancy** [comment]
the path is "\App_Data\Tenants\Default"
