### ISSUE TITLE
log4net is not included as NuGet package in git branch 3.x

### ISSUE THREAD

**Issue by iherwald** [smartstoreag/SmartStoreNET#1049]
Error CS0246 in project SmartStore.Core:
The type or namespace name 'log4net' could not be found (are you missing a using directive or an assembly reference?)

**Comment by muratcakir** [comment]
It **is** included. Enable NuGet package restore and try again please (or just recompile the solution).

**Comment by iherwald** [comment]
The compiling error occures after a fresh full checkout of branch 3.x.
Even to enable NuGet package restore and to recompile the solution does not solve the problem.

The reason is a missing line (7) in NuGet file
...src\Libraries\SmartStore.Core\packages.config

To add this entry, we can manually install the log4net package.
Package Manager Console:
Install-Package log4net -ProjectName SmartStore.Core

Or in NuGet file
...src\Libraries\SmartStore.Core\packages.config
the following line (7) has to be added:
<package id="log4net" version="2.0.5" targetFramework="net452" />

**Comment by muratcakir** [comment]
You're right! How could THAT happen? Has been fixed.
