### ISSUE TITLE
SmartStore installation failed with source from git branch 3.x

### ISSUE THREAD

**Issue by iherwald** [smartstoreag/SmartStoreNET#1050]
Error message on installation page:
Installation schlug fehl: An error occurred during installation. Stage: PopulateCurrencies (The conversion of a datetime2 data type to a datetime data type resulted in an out-of-range value. The statement has been terminated.)

Remarks:
Current database server: SQL Server Express 2014 (LocalDB)
Do we need to install SQL Server Express 2016?

**Comment by muratcakir** [comment]
The min. required database version is SQL Server Express **2008**. Maybe some of the latest commits affected the installation process. I'll dig into it.

**Comment by iherwald** [comment]
Installation runs successfully now.
