### ISSUE TITLE
SmartStore.Admin project tries to debug on remote server

### ISSUE THREAD

**Issue by serefbilge** [smartstoreag/SmartStoreNET#1054]
Hi,

SmartStore.Admin project tries to work from remote server which is "http://www.smartstore.net". So, when I try to debug in local it gives an error of "Unable to start debugging on the web server". How can I debug SmartStore.Admin project from local ?

**Comment by mgesing** [comment]
The "normal" way: Choose SmartStore.Web as start-up project. Open project properties, Web tab, and change the server settings. Or... change server settings of the Admin project.
