### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by ikhanal** [smartstoreag/SmartStoreNET#1070]
I have successfully installed the project once and would like to re-install (run locally for customization and testing purpose) with new database connection but got the following error:
The argument 'nameOrConnectionString' cannot be null, empty or contain only white space.

Tried: removing Setting.txt which has preious connection string
run with EFMigrations mode instead of Debugging Mode 
Run setting 
public MigrationsConfiguration()
		```
{
			AutomaticMigrationsEnabled = true;
			AutomaticMigrationDataLossAllowed = true;
			ContextKey = "SmartStore.Core";
		}
```
was unable to solve the problem.
Thank you

**Comment by muratcakir** [comment]
Are your working with the latest stable release or with current dev branch (3.x). If the latter is the case, please delete folder `App_Data\Tenants\Default`, not just the `Settings.txt` from App_Data.

BTW: `EFMigrations` is not meant to be started from. Never start a debugging session with this build configuration activated. Its only purpose is to help EF migration tooling to locate all required assemblies **during dev time**.

**Comment by ikhanal** [comment]
Thank you for your message. Bwy its 2.5 version that I have been working with so there is not /App-Data/Tenant folder.How can I solve in that older version?How about EF migration downgrading and updating ?Thank you
Get Outlook for iOS




On Thu, Dec 15, 2016 at 3:58 AM +1100, "Murat Cakir" <notifications@github.com> wrote:












Are your working with the latest stable release or with current dev branch (3.x). If the latter is the case, please delete folder App_Data\Tenants\Default, not just the Settings.txt from App_Data.


BTW: EFMigrations is not meant to be started from. Never start a debugging session with this build configuration activated. Its only purpose is to help EF migration tooling to locate all required assemblies during dev time.

**Comment by Michael-Herzog** [comment]
Old request & no real issue anyway.
