### ISSUE TITLE
During installation i am getting No constructor for Plugin was found that had all the dependencies satisfied.

### ISSUE THREAD

**Issue by reddy003** [smartstoreag/SmartStoreNET#1079]
![image](https://cloud.githubusercontent.com/assets/7783528/21489087/c3c7883a-cc0c-11e6-8bc7-28ba34b806e8.png)

**Comment by reddy003** [comment]
Please help me on this, what step i am missing here

**Comment by mgesing** [comment]
Please try download of a [released version](https://github.com/smartstoreag/SmartStoreNET/releases).
