### ISSUE TITLE
At least one shipping rate computation method provider is required to be active.

### ISSUE THREAD

**Issue by thinnv** [smartstoreag/SmartStoreNET#1083]
I get SourceCode from Git, but When i build and run Error :
Step 1: 
![image](https://cloud.githubusercontent.com/assets/6780364/21707089/d9baaf10-d3fe-11e6-964e-fa7e1c74451e.png)
Step 2:  click go to cart or click Checkout
![image](https://cloud.githubusercontent.com/assets/6780364/21707080/c2c2bc3a-d3fe-11e6-8161-379816a00b23.png)

Please,  Support for me?

**Comment by mgesing** [comment]
Please go to Plugins > Manage plugins in the admin area and ensure that the plugin "Shipping methods" (SmartStore.Shipping) or another computation method providing plugin is installed. Activate at least one method under Configuration > Regional Settings > Shipping rate computation methods.

**Comment by thinnv** [comment]
Thanks you

**Comment by AbuLaban** [comment]
I faced this issue, but i can't see any plugins, do I have to buy the plugin or what to do?
