### ISSUE TITLE
Install page cannot show complete

### ISSUE THREAD

**Issue by GerryGe** [smartstoreag/SmartStoreNET#1085]
Hi,
There's some problem in install page, can you help to check. Thanks!

![image](https://cloud.githubusercontent.com/assets/6952917/21989481/fddd1f64-dc45-11e6-9d52-556539150f80.png)

**Comment by muratcakir** [comment]
And what exactly is the problem (except the overflowed text)?

**Comment by januszt1987** [comment]
The problem is that there is no scrollbars and there is no chance to reach end of the form on my fullHD monitor.
![capture](https://cloud.githubusercontent.com/assets/14015424/22001910/3b5f15de-dc48-11e6-819c-9838961f35d5.PNG)

**Comment by muratcakir** [comment]
Found the cause: Please open file **Content/install/install.less** and remove or uncomment line 62:

`/*@import "~/Content/bootstrap/custom/custom.less";*/`

**Comment by GerryGe** [comment]
Thanks.
