### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by net4u** [smartstoreag/SmartStoreNET#1090]
Hi, 

I tried today to install the latest smartstore available and I get this error:
//
Setup failed: No constructor for Plugin was found that had all the dependencies satisfied.
//

Any hints please? (no errors at build time)
For reference at the time of error are all 108 tbls created in DB

**Comment by muratcakir** [comment]
Could you please post the contents of the latest install log file in `App_Data/Logs`

**Comment by net4u** [comment]
Here is my log:
[install-2017.01.26.log.txt](https://github.com/smartstoreag/SmartStoreNET/files/735856/install-2017.01.26.log.txt)
