### ISSUE TITLE
I cant add products to cart in product details page.

### ISSUE THREAD

**Issue by tiagobernardes** [smartstoreag/SmartStoreNET#1092]
I cant add products to cart in product details page.

Some help?

![capture](https://cloud.githubusercontent.com/assets/15774469/22669771/0f34dbe8-ecbe-11e6-999f-684c3cfb9086.PNG)

**Comment by Michael-Herzog** [comment]
This product template won't be used anymore in the future so you have to switch to the new product template or you just wait a few days until we make the new template the default one.
**Admin > Catalog > Manage Products > Product > Info > Product Template > Default Product Template**

**Comment by tiagobernardes** [comment]
In Product Template I have two options:
- Simple Product 
- Grouped Product

I don't have 'Default Product Template'

**Comment by Michael-Herzog** [comment]
Then you don't have the latest source code.

**Comment by tiagobernardes** [comment]
Ok, I'll update. thank you
