### ISSUE TITLE
Add new product throws NullReferenceException

### ISSUE THREAD

**Issue by nielshenriksen** [smartstoreag/SmartStoreNET#1097]
I am getting this error when trying to add a product under "Catalog" / "Manage products" / "Add new"

`[NullReferenceException: Object reference not set to an instance of an object.]
   SmartStore.Admin.Controllers.ProductController.PrepareProductModel(ProductModel model, Product product, Boolean setPredefinedValues, Boolean excludeProperties) in D:\Data\Dropbox\First Media IVS\Projekter\Shop\SmartStoreNET-3.x\src\Presentation\SmartStore.Web\Administration\Controllers\ProductController.cs:739
   SmartStore.Admin.Controllers.ProductController.Create() in D:\Data\Dropbox\First Media IVS\Projekter\Shop\SmartStoreNET-3.x\src\Presentation\SmartStore.Web\Administration\Controllers\ProductController.cs:1063
   lambda_method(Closure , ControllerBase , Object[] ) +86
   System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +228
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +34
   System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) +38
   System.Web.Mvc.Async.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) +66
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +41
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +71
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +386
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +386
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +386
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +386
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +386
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +386
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +42
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +38
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +186
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +38
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +29
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +65
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +53
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +36
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +38
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +44
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +65
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +38
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +399
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +137`

**Comment by net4u** [comment]
the same here, with clean install and no sample data.
![2017-02-14 1](https://cloud.githubusercontent.com/assets/255743/22928244/1c07d892-f2be-11e6-91f9-da1b9deab740.png)
![2017-02-14](https://cloud.githubusercontent.com/assets/255743/22928252/20f42a68-f2be-11e6-9574-ff617b3b997b.png)

**Comment by net4u** [comment]
I noticed that if I add a new delivery time, the exception move to line 820:
```
Line 818:
Line 819:			model.AvailableCountries = _countryService.GetAllCountries(true)
Line 820:				.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString(), Selected = x.Id == product.CountryOfOriginId })
Line 821:				.ToList();
Line 822:
```

**Comment by mgesing** [comment]
Thanks for the note!
