### ISSUE TITLE
Changing Jquery To Implement New Design Cause Telerik To Stop

### ISSUE THREAD

**Issue by hassanelsherbiny** [smartstoreag/SmartStoreNET#1109]
I have tried to Implement New Design Which Contain Jquery 1.8+ Which Caused Telerik Controls To Fail
how Can I Solve This Problem

**Comment by muratcakir** [comment]
The Telerik components are not compatible witj jQuery 1.8+. But I suppose this could be resolved with some _surrogate_ methods, which are not available anymore in later jQuery versions. But I didn't take a detailed look into this yet.
