### ISSUE TITLE
New installation failes before the installation page is showing up. Exception "The argument 'nameOrConnectionString' cannot be null..." (fresh checkout from current dev branch 3.x)

### ISSUE THREAD

**Issue by iherwald** [smartstoreag/SmartStoreNET#1115]
Exception detail:

 _System.ArgumentException was unhandled by user code
  HResult=-2147024809
  Message=The argument 'nameOrConnectionString' cannot be null, empty or contain only white space.
  Source=EntityFramework
  StackTrace:
       bei System.Data.Entity.Utilities.Check.NotEmpty(String value, String parameterName)
       bei System.Data.Entity.DbContext..ctor(String nameOrConnectionString)
       bei SmartStore.Data.ObjectContextBase..ctor(String nameOrConnectionString, String alias) in C:\MyProjects\Common\SmartStore\SmartStoreNET_sandbox\src\Libraries\SmartStore.Data\ObjectContextBase.cs:Zeile 37.
       bei SmartStore.Data.SmartObjectContext..ctor(String nameOrConnectionString) in C:\MyProjects\Common\SmartStore\SmartStoreNET_sandbox\src\Libraries\SmartStore.Data\SmartObjectContext.cs:Zeile 39.
       bei SmartStore.Web.Framework.DbModule.<>c.<Load>b__2_8(IComponentContext c) in C:\MyProjects\Common\SmartStore\SmartStoreNET_sandbox\src\Presentation\SmartStore.Web.Framework\DependencyRegistrar.cs:Zeile 405.
       bei Autofac.RegistrationExtensions.<>c__DisplayClass5_0`1.<Register>b__0(IComponentContext c, IEnumerable`1 p)
       bei Autofac.Builder.RegistrationBuilder.<>c__DisplayClass0_0`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p)
       bei Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
       bei Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
  InnerException:_ 

The error occures even after deleting the folder  _App_Data\Tenants\Default_

**Comment by mgesing** [comment]
I cannot reproduce it. What settings did you use for installation?

**Comment by iherwald** [comment]
I just compiled the solution from a fresh checkout and started SmartStore.Web in debug mode. The error occures while dependency registration, before the installation page is showing up. So I do not use any settings at this point.

Log file _...\App_Data\Logs\install-2017.03.28.log_ was created, but is empty.

**Comment by iherwald** [comment]
The initialization routines of SmartStore have changed since version 2.6, I guess due to the introduction of the tenant functionality.
Could you give some information about the current requirements for an installation targeting a new clean database in version 3.x?

**Comment by mgesing** [comment]
The root for tenant relevant things (like InstalledPlugins.txt, Settings.txt, _temp etc.) is not /App_Data anymore but /App_Data/Tenants/Default. If you need more tenants then create a new folder like /App_Data/Tenants/MyNewTenant. The name of the current tenant (like MyNewTenant) is entered
in /App_Data/Tenants/current.txt

The requirements/procedure for an installation targeting a new database has not changed. The mentioned resources just moved to /App_Data/Tenants/Default.

**Comment by iherwald** [comment]
Thank you for this information.
However, I do not provide a Settings.txt, neither in /App_Data nor in /App_Data/Tenants/Default.
With version 2.6 a new Settings.txt is created by SmartStore after a successfull installation.

But with Version 3.x an exception occures in ObjectContextBase **before** the installation page is showing up(please see first comment for stack trace info).

Could you try ro reproduce this with a fresh checkout of current 3.x?

**Comment by mgesing** [comment]
I do not get such an exception. The installation page is displayed normally. Did you try to delete the Temporary ASP.NET Files?

**Comment by iherwald** [comment]
I took the following steps:
- delete all files in Temporary ASP.NET Files
- did a fresh checkout of default branch 3.x (commit 84b4f51, 2017-04-07)  into an empty folder
- check that /App_Data/Tenants/Default is empty
- open solution in VS 2015 and rebuild it
- start SmartStore.Web in debug mode

Unfortunately the same exception occures again.
Followed that steps on a different machine (same OS: Windows 7 x64) and got that exception there as well.

**Comment by iherwald** [comment]
The cause for the error before the start of a new installation is located in method _AnonymousIdentification_Creating_ in _Global.asax.cs_. Here the CustomerService "is used to find a guest/anonymous customer record by client ident". Therefore a SmartObjectContext must be created, but fails because no database exists at that moment.

When the customer lookup in _AnonymousIdentification_Creating_ is deactivated (commented out), the installation page is showing up and the installation executes without any problems. I guess, to correct this the customer lookup should be skipped here if no database is fully initialized.

**Comment by mgesing** [comment]
Thank you for posting the reason of the problem.
