### ISSUE TITLE
menu dropdown bug

### ISSUE THREAD

**Issue by coolcode** [smartstoreag/SmartStoreNET#1124]
there is a menu dropdown bug in lastest version--
![image](https://cloud.githubusercontent.com/assets/182770/25787618/7941126c-33e6-11e7-9d00-15d2ffc476af.png)

**Comment by coolcode** [comment]
found the problem in    _megamenu.scss: 
I remove "position: relative;" ---
```
 .megamenu-dropdown-container {
        position: relative;
...
```
![image](https://cloud.githubusercontent.com/assets/182770/25790314/ebbe8b6c-33fa-11e7-8457-16f56a22a428.png)

**Comment by Michael-Herzog** [comment]
Thanks for reporting. This issue should be fixed now.
