### ISSUE TITLE
EntityFramework.SqlServerCompact Issue

### ISSUE THREAD

**Issue by JayakumarJK** [smartstoreag/SmartStoreNET#1125]
Hi

I face this error in your code can you give solution?

This is error
![shoopingcart-mvc-error](https://cloud.githubusercontent.com/assets/5018981/25803488/bac2031c-3414-11e7-90a3-4735ac25df5d.png)

=============
An exception of type 'System.Data.SqlServerCe.SqlCeException' occurred in EntityFramework.SqlServerCompact.dll but was not handled in user code

**Comment by muratcakir** [comment]
This is not a real exception, it is fired by Entity Framework on purpose to determine the current library version. Just ignore it and continue the debug session. Nothing bad will happen.

Nevertheless, I'll try to suppress this exception somehow.

**Comment by JayakumarJK** [comment]
Hi
The Error Message  Appears repeatedly, creating disturbance . How to fix it permanently
give solution give your personal email id then we will check teamviewer also

**Comment by muratcakir** [comment]
Please try it again with the latest commit from yesterday. I've fixed and enhanced some related stuff.
