### ISSUE TITLE
Error in Checkout Order in Debug mode

### ISSUE THREAD

**Issue by user151748** [smartstoreag/SmartStoreNET#1126]
Hello everybody!

I had to change the ordering logic and in the process of debugging, when go to the «Shipping» section, I get an error - SmartStoreExeption - "At least one shipping rate computation method provider is required to be active."

[SmartException: At least one shipping rate computation method provider is required to be active.]
SmartStore.Services.Shipping.ShippingService.LoadActiveShippingRateComputationMethods(Int32 storeId) in ...\SmartStoreNET-2.6.x\src\Libraries\SmartStore.Services\Shipping\ShippingService.cs:130
 
SmartStore.Services.Shipping.ShippingService.GetShippingOptions(IList`1 cart, Address shippingAddress, String allowedShippingRateComputationMethodSystemName, Int32 storeId) in ...\SmartStoreNET-2.6.x\src\Libraries\SmartStore.Services\Shipping\ShippingService.cs:387

SmartStore.Web.Controllers.CheckoutController.PrepareShippingMethodModel(IList`1 cart) in ...\SmartStoreNET-2.6.x\src\Presentation\SmartStore.Web\Controllers\CheckoutController.cs:192

SmartStore.Web.Controllers.CheckoutController.ShippingMethod() in ...\SmartStoreNET-2.6.x\src\Presentation\SmartStore.Web\Controllers\CheckoutController.cs:606

But in a configurator the «Shipping.FixedRate» method is marked as active.
 
If compile project in «Release», deploy project to IIS server, go to the app and do the same, then there is no error!

How to fix this error?

**Comment by Michael-Herzog** [comment]
Can't be reproduced. Maybe the solution wasn't built completely before th debug process was started.
