### ISSUE TITLE
Check-out button is not reachable (SmartStore 3.x)

### ISSUE THREAD

**Issue by iherwald** [smartstoreag/SmartStoreNET#1130]
User cannot click on the check-out button in shopping cart because the button is not reachable.

Browser: Internet Explorer 11

![checkout-button-not-reachable](https://cloud.githubusercontent.com/assets/3755359/26024286/ddf1a186-37ce-11e7-86d4-4b863ebe2c62.jpg)

(attached sreenshot)

**Comment by Michael-Herzog** [comment]
Thanks for reporting!
