### ISSUE TITLE
Displayed amount of shopping cart items in account dropdown is not in sync (SmartStore 3.x)

### ISSUE THREAD

**Issue by iherwald** [smartstoreag/SmartStoreNET#1133]
Displayed amount in account dropdown is not in sync:
- after the user added a new item to the cart or 
- the user increased the quantity of an item in Shopping cart

After a page refresh the displayed amout is in sync.

![shoppingcart-amount-is-not-in-snc](https://cloud.githubusercontent.com/assets/3755359/26054330/72ba2a06-396c-11e7-82ee-6d4e6b5d275f.jpg)

**Comment by muratcakir** [comment]
The dropdown badges are obsolete anyway. So I removed them entirely.
