### ISSUE TITLE
I can't upgrade from 2.6 to 3.0

### ISSUE THREAD

**Issue by nordic** [smartstoreag/SmartStoreNET#1138]
Is there documentation how can i upgrade to new version ? http://docs.smartstore.com/display/SMNET25/Updating+from+Previous+Versions
Thank you

**Comment by SilverSearcher** [comment]
I have the same issue

**Comment by SilverSearcher** [comment]
Okay I think this may have resolved my issue - 

Update nuget package manager - https://marketplace.visualstudio.com/items?itemName=NuGetTeam.NuGetPackageManagerforVisualStudio2013

Then do this:

    Opening up a command prompt
    Navigating to the .nuget folder in my solution
    Running nuget update -self
