### ISSUE TITLE
language 'order.orderdetails' cannot be loaded

### ISSUE THREAD

**Issue by coolcode** [smartstoreag/SmartStoreNET#1140]
![bug_20170522151137](https://cloud.githubusercontent.com/assets/182770/26294668/cfcdb446-3f08-11e7-9deb-37058adcde5a.png)

**Comment by muratcakir** [comment]
Please import the resource file located under `App_Data\Localization\App\en` and try again

**Comment by coolcode** [comment]
I had tried. it didn't work. FYI. I used the newest source code that i downloaded yesterday.

**Comment by Michael-Herzog** [comment]
Very weird problem. Is this the only textual resource that's missing? 
If so just added it in the admin area. Have you edited views? 
If so restore the originals again.

**Comment by coolcode** [comment]
No, I haven't changed anything. That should be the only one missing cause i haven't seen that another page like this. But the key 'order.orderdetails' exists in 'all.smres.xml' file. I dont know why it cannot be loaded.

**Comment by Michael-Herzog** [comment]
Please also check whether it exists in:
Admin > Configuration > Regional Settings > Languages > English > View String Resources

**Comment by coolcode** [comment]
Too many keys, my friend. (- . -!)
Can you provide a search function for it?

**Comment by Michael-Herzog** [comment]
There's a built-in filter method for the grid already implemented. 
(Each column has a little filter icon in the header)
