### ISSUE TITLE
Brand name is missing in "Customers who bought this..." slider

### ISSUE THREAD

**Issue by SilverSearcher** [smartstoreag/SmartStoreNET#1157]
Brand name (<div class="art-brand"><span>...) is missing in "Customers who bought this..." slider - but shows in "Recently viewed products" slider - should appear in both.

**Comment by Michael-Herzog** [comment]
It was implemented this way by design. You could change it in 
**SmartStore.Web > Controllers > ProductController > ProductsAlsoPurchased**

**Comment by SilverSearcher** [comment]
Hi - thanks.

I can see where you are taking about - but I'm unsure what I'd need to modify where. :(
