### ISSUE TITLE
SmartStore /Admin returns 404 Error

### ISSUE THREAD

**Issue by liuhaifancy** [smartstoreag/SmartStoreNET#1171]
Version 3.0 cann't login admin page,return 404 page.
Version 2.6 can login admin page.

I have deleted SmartStoreNET.Community.3.0.0\App_Data\Tenants\Default\InstalledPlugins.txt,also cann't login admin page.

Pls help me,ths.

**Comment by patsadow2** [comment]
First of all you should build a whole solution, Smart.Admin is not connected by reference to Smart.Web and when you click deploy only Smart.Web it doesn't build Admin :)
