### ISSUE TITLE
"Option sets" in product attribute details not working

### ISSUE THREAD

**Issue by mohsenns5** [smartstoreag/SmartStoreNET#1173]
Hi guys
"Option sets" in product attribute details not working for me. It not show in product page. Is there any document or sample about work with "Option sets"?
Thanks

**Comment by mgesing** [comment]
Option sets have no direct impact on the frontend. They allow the admin to map all values of a set to a product in one go. Example: http://demo.smartstore.com/backend/Admin/Product/Edit/260
Go to "Attributes", click "Edit" at "Farbe" and you will get a "copy set options" drop-down in column "Options". Unfortunately a documentation of this function is not available yet.
