### ISSUE TITLE
Error while downloading a downloadable product

### ISSUE THREAD

**Issue by h3x3ncr7pt** [smartstoreag/SmartStoreNET#1179]
when i buy something in the store (book) then i try to download it then i receive this error:

Internal Server Error

Controller: Download, Action: GetDownload 

The parameters dictionary contains a null entry for parameter 'orderItemId' of non-nullable type 'System.Guid' for method 'System.Web.Mvc.ActionResult GetDownload(System.Guid, Boolean)' in 'SmartStore.Web.Controllers.DownloadController'. An optional parameter must be a reference type, a nullable type, or be declared as an optional parameter. Parameter name: parameters

**Comment by mgesing** [comment]
Thank you for reporting.
