### ISSUE TITLE
Added a new table to db, how to use it ?

### ISSUE THREAD

**Issue by h3x3ncr7pt** [smartstoreag/SmartStoreNET#1180]
I added a new table to the db of smartstore.net, but the source code is very hard to understand, what code should i use to be able to use this table within the source code ?

_Sent from my Samsung SM-G900V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mgesing** [comment]
Best practise is use Entity Framework Fluent Migration (code first) as described [here](http://docs.smartstore.com/display/SMNET25/Entity+Framework+Migrations#EntityFrameworkMigrations-Howtoaddmigrationstoplugins). So it's more about to understand Fluent Migration rather than SmartStore.NET code.
