### ISSUE TITLE
error while browsing the store

### ISSUE THREAD

**Issue by h3x3ncr7pt** [smartstoreag/SmartStoreNET#1183]
when i try to access an item in the store i get an SQL error

Error 
`An exception of type 'System.Data.SqlClient.SqlException' occurred in System.Data.dll but was not handled in user code
Additional information: Invalid column name 'CreatedOn'.
`
 in this code : 

`protected override DbDataReader ExecuteDbDataReader(CommandBehavior behavior)
		{
			if (!IsCacheable)
			{
				var result = _command.ExecuteReader(behavior);

				if (!_commandTreeFacts.IsQuery)
				{
					_cacheTransactionInterceptor.InvalidateSets(Transaction, _commandTreeFacts.AffectedEntitySets.Select(s => s.Name));
				}

				return result;
			}`

and exactly in this line 

`var result = _command.ExecuteReader(behavior)`

**Comment by mgesing** [comment]
Please see this [post](http://community.smartstore.com/index.php?/topic/48608-shipping-plugin-installation-execute-task-is-throwing-error-invalid-column-name-createdon/?p=272530).
