### ISSUE TITLE
Search: Do not hide multi-selectable filters of the same group if there are no hits

### ISSUE THREAD

**Issue by iherwald** [smartstoreag/SmartStoreNET#1187]
Filter options for "brands" and "delivery times" are correctly rendered for multi selection as "check boxes" but are behaving like "radio buttons". Only selection of one option is possible.

**Comment by mgesing** [comment]
Could you please provide more details? I could not reproduce it.

**Comment by iherwald** [comment]
In the Community Edition v3.0.1 multi selection of filter options is not possible.

However, in the demo store "http://demo.smartstore.com/frontend" multi selection of check boxes is working as expected.

**Comment by mgesing** [comment]
I cannot reproduce that. Works as expected. Manufacturers and delivery times are filtered "or-combined".

**Comment by iherwald** [comment]
The root cause for the described behaviour in Community Edition is, that all manufactures existing in the shop are listed as brand filter options, regardless which category and other filter options are currently active.

I guess this is due to limitations in the Community Edition (?)
However, as a user you have to get grip on it first.

**But nevertheless this results in an inconsistent behaviour:**

- If the user _first_ selects a brand option that _none_ of the products in the active category and other filter options can fulfill, all other brand options are removed.
- If the user _first_ selects a brand option that _at least one_ of the products in the active category and other filter options can fulfill, all other brand options remain and are selectable.

Steps to test it with Community Edition:

Download and extract SmartStoreNET Community v3.0.1:
https://github.com/smartstoreag/SmartStoreNET/releases/download/3.0.1/SmartStoreNET.Community.3.0.1.zip
Run SmartStoreNET in WebMatrix
Create new SQL Server Express database and install SmartStoreNET with sample data

**Test A:**
1. Select category "Sports"
2. Select "Brand" filter option "Acer"
-> Results in: all other brand options are removed.

Remove all filters

**Test B:**
1. Select category "Sports"
2. Select "Brand" filter option "Adidas"
3. Select "Brand" filter option "Acer"
-> Results in: all other brand options remain and are selectable.
