### ISSUE TITLE
Product import throws exception "Cannot insert duplicate key row in object 'dbo.IndexBacklog' with unique index 'IX_HashCode'."

### ISSUE THREAD

**Issue by mgesing** [smartstoreag/SmartStoreNET#1191]
[logfile.txt](https://github.com/smartstoreag/SmartStoreNET/files/1108600/logfile.txt)

**Comment by muratcakir** [comment]
Actually fixed in 3.0.1. Are you sure that import was performed in 3.0.1?

**Comment by mgesing** [comment]
Yes, see log file.
