### ISSUE TITLE
price filter is applied to store primary currency, not current selected currency

### ISSUE THREAD

**Issue by SalehGladius** [smartstoreag/SmartStoreNET#1194]

**Comment by mgesing** [comment]
Yes indeed but that would require converted prices to be stored in the database and to be frequently updated against changes of exchange rates and product updates made by the merchant.
A bit too much just for price filtering, in my opinion.

However the MegaSearch plugin is based on Lucene and the Lucene index works like a temporary storage that is frequently updated. That allows to store converted prices in the index and
to filter prices based on the selected currency.
