### ISSUE TITLE
No low stock activity when bulk editing the product quantity

### ISSUE THREAD

**Issue by rzpatel** [smartstoreag/SmartStoreNET#1207]
Version 3.0

If one has selected the option to disable the buy button when product is out of stock, the Add to Cart button is not displayed [expected behaviour]

When you increase the stock quantity on the product edit page, Add to cart shows up on the product page. [expected behavior]

Instead of updating the inventory from the product edit page and updating via bulk edit.... inventory shows up in stock but the Add to cart button does not show up.

**Comment by mgesing** [comment]
Thank you for reporting.
