### ISSUE TITLE
Vendor implementation

### ISSUE THREAD

**Issue by muratcakir** [smartstoreag/SmartStoreNET#122]
Is it possible implement a vendor functions ? 

> Migrated from CodePlex: [Issue #117](https://smartstore.codeplex.com/workitem/117) from [msavara](https://www.codeplex.com/site/users/view/msavara), on 10/15/2013 4:56:49 PM

**Comment by mgesing** [comment]
[Duplicate.](https://github.com/smartstoreag/SmartStoreNET/issues/811)
