### ISSUE TITLE
Right cart menu is not hiding by click in Chrome (aside offcanvas-cart)

### ISSUE THREAD

**Issue by prazak** [smartstoreag/SmartStoreNET#1238]
In Chrome the hiding of the right cart menu (cart,wishlit,compare) is not working by click anywhere.
So on Chrome browser there is no possibility to close the menu and continue shopping.

**Comment by muratcakir** [comment]
Not reproducable:
* Which version of Chrome?
* Any errors shown in Chrome's console?

**Comment by prazak** [comment]
No errors in console.
Version 60.0.3112.101 (64b)
On IE it is working fine. On our server in Chrome (same version) it is working fine. 
I am not sure why it should not be working on my PC only... but it is maybe problem only on my Chrome installation, while you cannot reproduce it.

**Comment by dnxit** [comment]
I'm also facing the same issue, don't you think a button in the right cart menu will be a good backup.

Chrome Version 63.0.3239.132 (Official Build) (64-bit)

Console Errors:

Failed to load resource: the server responded with a status of 404 (Not Found)
jquery-migrate-3.0.0.js:18 JQMIGRATE: Migrate is installed with logging active, version 3.0.0
globalize.culture.en-US.js Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by rhinterndorfer** [comment]
Same issue here with version 3.1.5
Happens in Chrome Version 68.0.3440.106 (Official Build) (64-bit) and Firefox 62.0 (64-bit).
There are no errors in developer console.
On IE and Edge it works fine.

As workaround I placed a close button within the flyout.
Add following lines to Views\ShoppingCart\Partials\OffCanvasCart.cshtml (line 43)
```
<li class="nav-item">
<a id="close-tab" class="nav-link" data-toggle="offcanvas" data-target="#offcanvas-cart" href="#">
	<span class="title">X</span>
</a>
</li>
```

**Comment by AbdonDeKousemaeker** [comment]
Clear your cash of the browsers, works fine here.

Met vriendelijke groet, Best regards, Mit freundlichen Grüßen, Cordialement
KOOMBA b.v.

Abdon De Kousemaeker
Mobile: +31 612 8380 12
E-mail: abdon@koomba.eu
Postadres:
Postbus 1632
3260 BC  OUD-BEIJERLAND

Tel:  +31 10 204 55 25
Fax: +31 10 204 55 55

Brainpark II Rotterdam
Lichtenauerlaan 102
3062 ME  ROTTERDAM
www.koomba.eu

**Comment by rhinterndorfer** [comment]
It seems to be a problem with touch enabled devices. My notebook has a touch screen and when using touch input everything works great but not when using mouse clicks to operate the site.
Within Chrome their is a flag (chrome://flags - Touch Events API) to disable touch support. When I disable the touch API mouse click starts to work.
