### ISSUE TITLE
TaskScheduler Polling Issue - Email/Task fail to run

### ISSUE THREAD

**Issue by SilverSearcher** [smartstoreag/SmartStoreNET#1254]
Hi - Please any help with this would be greatly appreciated... I've lost my hair!!! - getting and issue with the TaskScheduler and polling where it sits and waits to perform tasks. (3.0.0)

The task scheduler cannot poll and execute tasks. Base URL: https://domain.store/TaskScheduler, Status: The operation has timed out. Please specify a working Base URL in web.config, setting 'sm:TaskSchedulerBaseUrl'. I've tried setting a BaseURL both http/https - but nothing. I've even tried url-rewrite to capture both (if it finds it)

It's been intermittent but did seem to work a little better and ran for a while (but not much) on HTTP vs. HTTPS in which it won't work at all. I've set "store" values/hosts/ssl etc. and "general settings > security" ssl to see which/any combinations work and I've nothing. Localhost was working fine, but that's not my concern... I'm looking to production.

If there any known issue with SSL or domains that don't have //www. or //sub.domain? -- Also, I'm getting this: (I can ping: xxx.31.189.219:443)

System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond xxx.31.189.219:443
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

**Comment by muratcakir** [comment]
If TaskScheduler polling does not work out-of-the-box, you need to ensure that the URL specified in web.config is accessible by the webserver. This depends on how your your webserver is configured and has nothing to do with the software itself. The server must be able to call himself somehow.

The easiest way to test this is: use a browser **directly on the production server** and type the URL `http(s)://[Host]/taskscheduler/noop` (replacing [Host] with either _localhost_, IP address, domain name etc.). If a page appears and sais _noop_, then this the URL you need to specify in web.config.

**Comment by SilverSearcher** [comment]
Hi - thanks for your response... trying to give back here, because I solved the issue for multiple scenarios - so I want to leave solutions for those that may encounter the same.

For HTTP - per you reply for HTTP. Need to change web.config as follows; on the main server that is hosting the solution: {IP on web.config differs on different machines e.g. dev, stage, pro)

From: <add key="sm:TaskSchedulerBaseUrl" value="~/TaskScheduler" />
To: <add key="sm:TaskSchedulerBaseUrl" value="http://[HOSTIP][PORT]/TaskScheduler" /> (Machine IP - not domain)
e.g. <add key="sm:TaskSchedulerBaseUrl" value="http://10.x.x.10:100/TaskScheduler" />

I'm running SSL, and no matter what I tried - changing http to https on the above failed to run TaskScheduler. So after about 2 days of thinking and attempts at different solutions; I have this -

Using URL-Rewrite: https://www.iis.net/downloads/microsoft/url-rewrite

Add the following to the web.config - (not elegant; but helps routing of http to https; while excluding any localhost or localhost IP - which should be the IP of the hosting machine.) Essentially, this allows the http:// version or IP'd version of the /TaskScheduler to run without hitting HTTPS and stopping; which works!

<system.webServer>
    <rewrite>
		  <rules>
			  <rule name="HTTP to HTTPS Redirect" enabled="true" stopProcessing="true">
			  <match url="(.*)"/>
			  <conditions>
			  <add input="{HTTP_HOST}" matchType="Pattern" pattern="^localhost(:\d+)?$" negate="true" />
			  <add input="{HTTP_HOST}" matchType="Pattern" pattern="^127\.0\.0\.1(:\d+)?$" negate="true" />
			  <add input="{HTTP_HOST}" matchType="Pattern" pattern="^10\.0\.0\.10(:\d+)?$" negate="true" />
			  <add input="{SERVER_PORT_SECURE}" pattern="^0$" />
			  </conditions>
			  <action type="Redirect" url="https://{HTTP_HOST}/{R:1}" redirectType="Permanent" />
			  </rule> 
		  </rules>
	  </rewrite>


Finally, make sure that "Config > Store" - SSL check and SSL URL are ONLY in place on your production machine that also contains your SSL certificate... if you develop on a dev/stage with no SSL and you select these options - you'll lock yourself out of the /admin because it creates an error with the https lookback.

My preference here was to leave them unchecked any - because the host SSL is handling it by default.

I hope this helps. Thanks for your input - always appreciated.

**Comment by SilverSearcher** [comment]
These are resolved by the above and version 3.0.2 - I still have an issue with the contact us from email sticking in the queue, but it doesn't disrupt other email.
