### ISSUE TITLE
Error during saving in Manage product [admin] page

### ISSUE THREAD

**Issue by FloteFuertes** [smartstoreag/SmartStoreNET#1263]
![capture1](https://user-images.githubusercontent.com/21190507/30489568-2371e132-9a6a-11e7-985e-f3c4075b066f.JPG)
![capture3](https://user-images.githubusercontent.com/21190507/30489569-23730968-9a6a-11e7-80a5-99220ef74049.JPG)

**Comment by muratcakir** [comment]
You shouldn't work in **bs4-admin** branch, it's work in progress and at this stage rather experimental. Please switch over to **master** or **3.x**.
