### ISSUE TITLE
Smartstore.core error

### ISSUE THREAD

**Issue by FloteFuertes** [smartstoreag/SmartStoreNET#1301]
I have another error 
![image](https://user-images.githubusercontent.com/21190507/32401375-ee9a454e-c147-11e7-98d0-2f349a2cde2f.png)
@muratcakir

**Comment by muratcakir** [comment]
Seems to be a deployment issue. Rebuild the solution or restore all nuget packages and try again please.

**Comment by FloteFuertes** [comment]
ok I found the solution..What I did is I revert the version of autofac from 4.5 to 4.3 and now it's all working.
