### ISSUE TITLE
Clearing Installation/setup and reinstalling with empty db.

### ISSUE THREAD

**Issue by Farruuu** [smartstoreag/SmartStoreNET#1305]
Hi Guys,

I just tried your Application, and I must Say you have done great job. 
I need you help regarding Initial Setup of this Application. I installed it with an existing DB in my System. But now I want to install it with an Empty DB that is created automatically. 

Can you please help me how can I uninstall this Application from my System and reinstall/configure with an empty db. 
Thanks in advance.

**Comment by mgesing** [comment]
An uninstallation is not required. Just remove the file App_Data\Tenants\Default\Settings.txt and the shop opens with the installation page.
