### ISSUE TITLE
ClickToBuild.bat results in over 200 errors - VS2017

### ISSUE THREAD

**Issue by Legends** [smartstoreag/SmartStoreNET#1314]
How can I build the solution without getting errors?
I tried the batch file several times and afterwards VS2017 for building.
Somehow the packages are not downloaded:

> D:\SmartStoreNET-3.0.3\SmartStoreNET-3.0.3\src\.nuget\NuGet.targets(92,9): error : Unable to find version '6.1.3
>        ' of package 'EntityFramework.SqlServerCompact'. [D:\SmartStoreNET-3.0.3\SmartStoreNET-3.0.3\src\Tests\SmartStor
>        e.Data.Tests\SmartStore.Data.Tests.csproj]
>      5>D:\SmartStoreNET-3.0.3\SmartStoreNET-3.0.3\src\.nuget\nuget.targets(92,9): error : Unable to find version '4.0.8
>        876.1' of package 'Microsoft.SqlServer.Compact'. [D:\SmartStoreNET-3.0.3\SmartStoreNET-3.0.3\src\Libraries\Smart
>        Store.Data\SmartStore.Data.csproj]
>     24>D:\SmartStoreNET-3.0.3\SmartStoreNET-3.0.3\src\.nuget\NuGet.targets(92,9): error : Unable to find version '4.0.8
>        876.1' of package 'Microsoft.SqlServer.Compact'. [D:\SmartStoreNET-3.0.3\SmartStoreNET-3.0.3\src\Tests\SmartStor
>        e.Data.Tests\SmartStore.Data.Tests.csproj]
>      5>D:\SmartStoreNET-3.0.3\SmartStoreNET-3.0.3\src\.nuget\nuget.targets(92,9): error : Unable to find version '11.0.
>        2100.61' of package 'Microsoft.SqlServer.Scripting'. [D:\SmartStoreNET-3.0.3\SmartStoreNET-3.0.3\src\Libraries\S
>        martStore.Data\SmartStore.Data.csproj]
>     24>D:\SmartStoreNET-3.0.3\SmartStoreNET-3.0.3\src\.nuget\NuGet.targets(92,9): error : Unable to find version '2.6.3
>        ' of package 'NUnit'. [D:\SmartStoreNET-3.0.3\SmartStoreNET-3.0.3\src\Tests\SmartStore.Data.Tests\SmartStore.Dat
>        a.Tests.csproj]
>      5>D:\SmartStoreNET-3.0.3\SmartStoreNET-3.0.3\src\.nuget\nuget.targets(92,9): error : Unable to find version '10.0.
>        2' of package 'Newtonsoft.Json'. [D:\SmartStoreNET-3.0.3\SmartStoreNET-3.0.3\src\Libraries\SmartStore.Data\Smart
>        Store.Data.csproj]

**Comment by AbdonDeKousemaeker** [comment]
Hi,
Open the solution.
Right click on the project. Restored Nuget, clean solution, rebuild, click to build

**Comment by Legends** [comment]
Doesn't fix it!

Click on "Restore nuget packages":7
All packages are already installed and there is nothing to restore.
Time Elapsed: 00:00:00.0673254
========== Finished ==========

Let's take the EntityFramework nuget package for example, it's folder under packages does not contain the dll, only xml files:

> SmartStoreNET-3.0.3\src\packages\EntityFramework.6.1.3\lib\net45



![image](https://user-images.githubusercontent.com/966368/33396890-42bda632-d54a-11e7-8aa9-7c5730950feb.png)

**Comment by Legends** [comment]
I solved it by deleting the packages folder, `nuget restore YourSolution.sln`
and `Update-Package -reinstall` and 

> adding references manually

, it was hell, but now it works.
