### ISSUE TITLE
Question: Keyword not supported: 'initial catalog'

### ISSUE THREAD

**Issue by Legends** [smartstoreag/SmartStoreNET#1316]
This is a question:

I have installed the SmartStoreNET.Community.3.0.3.zip locally on Win10, IIS v10, backend is SQL 2016.
Works perfectly.

I also managed to build the solution of "Source code (zip) v3.0.3" successfully.
When I hit F5 to run the app in VS2017 (IIS Express), I get to the install page and there I enter the same SQL database that I use for the deployed release version "SmartStoreNET.Community.3.0.3.zip". This works fine.

But after successfull install I get the error mentioned in the title at line 47, ObjectContextBase.cs (SmartStore.Data):
this call:  `var migrator = new DbSeedingMigrator<SmartObjectContext>();` does not succeed.
`	((IObjectContextAdapter)this).ObjectContext.ObjectMaterialized += ObjectMaterialized;`

Any tip what the issue could be? Here the full stack trace:

>    at System.Data.SqlServerCe.SqlCeConnectionStringBuilder.GetIndex(String keyword)
>    at System.Data.SqlServerCe.SqlCeConnectionStringBuilder.set_Item(String keyword, Object value)
>    at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
>    at System.Data.SqlServerCe.SqlCeConnectionStringBuilder..ctor(String connectionString)
>    at System.Data.SqlServerCe.SqlCeConnection.set_ConnectionString(String value)
>    at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.<SetConnectionString>b__18(DbConnection t, DbConnectionPropertyInterceptionContext`1 c)
>    at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
>    at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.SetConnectionString(DbConnection connection, DbConnectionPropertyInterceptionContext`1 interceptionContext)
>    at System.Data.Entity.Infrastructure.SqlCeConnectionFactory.CreateConnection(String nameOrConnectionString)
>    at System.Data.Entity.Internal.LazyInternalConnection.Initialize()
>    at System.Data.Entity.Internal.LazyInternalConnection.get_ProviderName()
>    at System.Data.Entity.Internal.LazyInternalContext.get_ProviderName()
>    at System.Data.Entity.Internal.DefaultModelCacheKeyFactory.Create(DbContext context)
>    at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
>    at System.Data.Entity.Internal.InternalContext.ForceOSpaceLoadingForKnownEntityTypes()
>    at System.Data.Entity.DbContext.System.Data.Entity.Infrastructure.IObjectContextAdapter.get_ObjectContext()
>    at SmartStore.Data.ObjectContextBase..ctor(String nameOrConnectionString, String alias) in D:\SmartStoreNET-3.0.3\SmartStoreNET-3.0.3\src\Libraries\SmartStore.Data\ObjectContextBase.cs:line 47
>    at SmartStore.Data.ObjectContextBase..ctor() in D:\SmartStoreNET-3.0.3\SmartStoreNET-3.0.3\src\Libraries\SmartStore.Data\ObjectContextBase.cs:line 32
>    at SmartStore.Data.SmartObjectContext..ctor() in D:\SmartStoreNET-3.0.3\SmartStoreNET-3.0.3\src\Libraries\SmartStore.Data\SmartObjectContext.cs:line 34
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Data.Entity.Infrastructure.DbContextInfo.CreateInstance()
>    at System.Data.Entity.Infrastructure.DbContextInfo..ctor(Type contextType, DbProviderInfo modelProviderInfo, AppConfig config, DbConnectionInfo connectionInfo, Func`1 resolver)
>    at System.Data.Entity.Migrations.DbMigrator..ctor(DbMigrationsConfiguration configuration, DbContext usersContext, DatabaseExistenceState existenceState, Boolean calledByCreateDatabase)
>    at System.Data.Entity.Migrations.DbMigrator..ctor(DbMigrationsConfiguration configuration)
>    at SmartStore.Data.Setup.DbSeedingMigrator`1..ctor(DbMigrationsConfiguration configuration) in D:\SmartStoreNET-3.0.3\SmartStoreNET-3.0.3\src\Libraries\SmartStore.Data\Setup\DbSeedingMigrator.cs:line 37
>    at SmartStore.Data.Setup.DbSeedingMigrator`1..ctor() in D:\SmartStoreNET-3.0.3\SmartStoreNET-3.0.3\src\Libraries\SmartStore.Data\Setup\DbSeedingMigrator.cs:line 28
>    at SmartStore.DevTools.DevToolsPlugin.HasPendingMigrations()

**Comment by muratcakir** [comment]
You're definitely using the dev branch (3.x) and not the stable 3.0.3 release. What you report is a bug which appeared during 3.1 development but has been fixed already. Please switch back to the latest 3.0.3 stable release.

**Comment by Legends** [comment]
I have downloaded this source code and it's definitely v3.0.3. Here is the link:
[https://github.com/smartstoreag/SmartStoreNET/archive/3.0.3.zip](url)

Can you kindly point me to the fix of this bug?

**Comment by muratcakir** [comment]
This exception implies that SmartStore tries to laod the SQL CE provider for EF. Something went wrong with the SQL Server installation and the system tries to fallback to SQL CE. Can you check whether the SQL database has been created and seeded correctly?

**Comment by nadarmuthukumar** [comment]
I'm facing this same issue in the latest 4.x branch.
![image](https://user-images.githubusercontent.com/5547364/87913334-8c854d80-ca8c-11ea-9568-f54551894914.png)
Although I've set up the project as a SQL server express project but it is picking SQL compact.
Kindly help me fix the issue.
