### ISSUE TITLE
Error when click Admin menu (HTTP Error 404.0 - Not Found)

### ISSUE THREAD

**Issue by levantam** [smartstoreag/SmartStoreNET#1317]
I checked all issues about this error in Issues tab but I couldn't log into the admin panel. So I re-open the issue.

My steps:
- Clone project from GitHub site 
- Restore all NuGet packages
- Clean and rebuild solution
- Run project SmartStore.Web: install project successfully and log into website (use admin account)
- Click Admin link (http://localhost:58519/admin) => Error HTTP Error 404.0 - Not Found

![image](https://user-images.githubusercontent.com/4737016/33595824-21a37180-d9cc-11e7-9479-707e380991f3.png)

Please help me check this error.
Thank you

**Comment by mgesing** [comment]
Please ensure not to compile with build configuration "PluginDev".

**Comment by levantam** [comment]
Hi mgesing, all build configurations are set with Debug mode

**Comment by haidoor** [comment]
I am having the exact same issue.

Appreciate your help.

Thank you

**Comment by levantam** [comment]
Checked bin folder of Community version and SmartStore project, I saw that: in SmartStore.Web project missed one dll: **SmartStore.Licensing.dll**
Temporary solution (worked with me)

1. Download community version 
https://github.com/smartstoreag/SmartStoreNET/releases/download/3.0.3/SmartStoreNET.Community.3.0.3.zip
2. Copy file **SmartStore.Licensing.dll** from bin folder of community version to bin folder of SmartStore.Web project

Run the project and check admin page.
@mgesing Please help review my solution. If this is illegal, I will delete this comment.
Thanks,
Tam Le

**Comment by mgesing** [comment]
Thank you for the solution, Tam Le. Everything's fine. I've set "Copy local" to True for that assembly reference and it now should be copied to the bin folder again.
