### ISSUE TITLE
Price facets can end in infinite loop

### ISSUE THREAD

**Issue by pineportal** [smartstoreag/SmartStoreNET#1322]
If the minimum and maximum product prices are high in the category. For example, 5 and 9 billion.
When it comes to making the price filter, it stays in a very large cycle

![ddddd](https://user-images.githubusercontent.com/31403448/33942607-b191eb90-e02b-11e7-94af-3a9b35e5fe3e.jpg)

**Comment by mgesing** [comment]
Thank you for reporting.
