### ISSUE TITLE
Product Import: Image folder name not linking after renaming task

### ISSUE THREAD

**Issue by CompleteCoders** [smartstoreag/SmartStoreNET#1324]
When you create the profile it is called something like "my product import 1".  This creates a folder of the same name on the server in the  \App_Data\Tenants\Default\ImportProfiles\ folder structure called my product import 1.  If you rename the profile to something useful like "National Promo Import" the folder on the server doesn't get renamed.  There is no longer a link from what folder is used on the server to the name of the profile.

Solution 1:  When a profile is renamed, also rename the folder on the server.

Solution 2:  Show the directory on the profile screen that is used by the service.  

Partial Solution: Give the user the ability to choose the name when the upload the file and don't let them rename it.  This way the folder structure is maintained.  If they don't like the name they can recreate.

**Comment by mgesing** [comment]
There is no need for the folder name to be editable, renamed or to follow the profile name. But by [this commit](https://github.com/smartstoreag/SmartStoreNET/commit/d71e72e7fb292b216d1aad18075989d7045c5ce1) the name is now displayed in the profile settings.
