### ISSUE TITLE
Shopping cart skipping payment step

### ISSUE THREAD

**Issue by CompleteCoders** [smartstoreag/SmartStoreNET#1327]
Setup:
1. Setup a FedEx plugin to offer shipping
2. Setup a $0.00 "Fixed rate shipping method"
3. Add a $0.00 item to the cart

Steps to Reproduce:
1. Go to shipping step in cart
2. Choose free shipping method, hit next
3. Should be on the Confirm step
4. Hit Back
5. Choose a fedex option that has a cost, hit next
6. You arrive at Confirm step.

Expected Result
- You should be asked to enter a payment method.

Note: There is an issue if you do the reverse process as well.  If you first choose a shipping method with a cost and then go back and move to a free one the payment method still appears on the confirm screen.

**Comment by mgesing** [comment]
Thank you for reporting.
