### ISSUE TITLE
Tiered Pricing on Bundled Products

### ISSUE THREAD

**Issue by rzpatel** [smartstoreag/SmartStoreNET#1333]
Tiered pricing [Fixed} does not appear to take effect on bundled products.

**Comment by mgesing** [comment]
Can you please give more details on the problem?

**Comment by rzpatel** [comment]
Thank You for your response. Unfortunately I am not able to consistently reproduce the error. I believe it may have something to do with the price update in the mini cart. I also noticed sometimes for bundled products I am not able to see the item counter next to the add to cart button. I will test this further and once I am able to consistently reproduce I will respond back with the steps.
