### ISSUE TITLE
The security issue is to save the file in the host

### ISSUE THREAD

**Issue by pineportal** [smartstoreag/SmartStoreNET#1335]
Download files that are also money are stored on the following path
~/Media/Default/Downloads/0000001-0.rar
~/Media/Default/Downloads/0000020-0.rar
A store may only have zipped files. One person reviewing the project. 
It can download all file without paying.
Please route the files from the folder Media change App_Data folder.
tnx

**Comment by muratcakir** [comment]
Implemented already for V3.1 (media folder has been moved to App_Data/Tenants/*/Media)
