### ISSUE TITLE
Product Review Mapping with customer

### ISSUE THREAD

**Issue by FarrukhRB** [smartstoreag/SmartStoreNET#1337]
Hi,

        I'm learning MVC Using this project. This is not actually an Issue, but I'm unable to find or track how product reviews displayed on Product Review List retrieve customer name, when there is no direct link between product Review and Customer Tables. 

Can you please explain how this is managed. 
Thanks in advance.

**Comment by mgesing** [comment]
[ProductReview entity](https://github.com/smartstoreag/SmartStoreNET/blob/3.x/src/Libraries/SmartStore.Core/Domain/Catalog/ProductReview.cs#L9) inherits the customer relationship from the CustomerContent entity. Details about the Entity Framework inheritance feature can be found [here](https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/getting-started-with-ef-using-mvc/implementing-inheritance-with-the-entity-framework-in-an-asp-net-mvc-application).
