### ISSUE TITLE
Complete Refunding an order that is already partially refunded

### ISSUE THREAD

**Issue by FarrukhRB** [smartstoreag/SmartStoreNET#1348]
Please look into the issue as when an order that is partially refunded is refunded completely. wrong amount is refunded. 

after initial partial refund, I clicked "mark As Paid" and refunded complete again. this raised this issue.

![complete refund](https://user-images.githubusercontent.com/5442605/34766290-bfe4841e-f615-11e7-8749-164a17fc24b0.png)
![partial refunded](https://user-images.githubusercontent.com/5442605/34766291-c019133c-f615-11e7-90a8-8ee839bc64ee.png)

**Comment by mgesing** [comment]
I cannot reproduce that. The Cash On Delivery payment provider (Payments.CashOnDelivery) does not support refunding or partial refunding. How do you refund when the provider does not support it?

**Comment by FarrukhRB** [comment]
I might have configured something wrong, but as The screenshots attached showed this is happening. 
Let me know what mistake I've done while configuring payment methods.

**Comment by mgesing** [comment]
I was able to reproduce it according to your steps using offline refunding. It's probably a bug.

**Comment by FarrukhRB** [comment]
I guess Its fixed. How can I Get the latest code. I'm not using GIT branch but had it downlo

**Comment by FarrukhRB** [comment]
I guess Its fixed. How can I Get the latest code. I'm not using GIT branch but had it downloaded zipped.

**Comment by mgesing** [comment]
Git clone or zip download 3.x branch. But I would wait for the next official release. It's just a little bug. After a partial refund, the refund button must not be displayed anymore. In other worde, after a partial refund only further partial refunds are possible.

**Comment by FarrukhRB** [comment]
Alright Thanks. I guess waiting for next Update would be a better option.
