### ISSUE TITLE
Setup failed: An error occurred during installation. Stage: PopulateMessageTemplates

### ISSUE THREAD

**Issue by csharp007** [smartstoreag/SmartStoreNET#1352]
Getting the following error while installing. Please help

"Setup failed: An error occurred during installation. Stage: PopulateMessageTemplates (Could not obtain an email templates path for language en-US. Fallback to 'en' failed, because directory does not exist.)"

**Comment by muratcakir** [comment]
Cannot reproduce. It seems that the directory `/App_Data/EmailTemplates/en/` is missing on your machine, but why?
