### ISSUE TITLE
No Public Access - Mobile site login page calling to menu without permission

### ISSUE THREAD

**Issue by CompleteCoders** [smartstoreag/SmartStoreNET#1359]
Turn off all public access to the store so that login is requested first.

_Document.cshtml makes a call to a function in public.offcanvas-menu.js.  this seems to make a call to pull down menu items.  The function seems to keep calling to get the menu items but because guest access it turned off, it doesn't allow the call to go through.  It get blocked in "PublicStoreAllowNavigationAttributes.cs"

This loop on my iPhone 7 makes logging in impossible.  Now I think the correct fix is to NOT get the menu when the Guest Access to public store is turned off and the user is not logged in..  But I'm not 100% positive I understand why it is calling for the menu.

**Comment by CompleteCoders** [comment]
Here is how we fixed for our site.  We just excluded the login page from the ajax call to get the menu.  I doubt this is how you would want it fixed long term in the system but it fixed it for us for now.  


[public.offcanvas-menu.zip](https://github.com/smartstoreag/SmartStoreNET/files/1657160/public.offcanvas-menu.zip)

**Comment by Michael-Herzog** [comment]
Thanks for reporting!
