### ISSUE TITLE
x-editable: refactor DateTime UI type adapter

### ISSUE THREAD

**Issue by muratcakir** [smartstoreag/SmartStoreNET#1366]
* SMNET uses [tempusdominus](https://tempusdominus.github.io/bootstrap-4/) for Bootstrap 4 (see `~/Content/vendors/datetimepicker`)
* Usage see `~/Views/EditorTemplates/DateTime.cshtml`
* Refactor lines 6411 - 6653: incorporate tempusdominus instead of default bootstrap-datetimepicker.
* Remove code for `bootstrap-datepicker` (6099 - ?)
* Remove embedded bootstrap-datepicker.js library (4843 - ?)
* Remove CSS for any datepicker widget from `x-editable.css`
* Ensure that standalone datetimepicker works while x-editable script is included in page (at the moment it doesn't)

**Comment by pineportal** [comment]
http://eonasdan.github.io/bootstrap-datetimepicker/

**Comment by pineportal** [comment]
https://github.com/pingcheng/bootstrap4-datetimepicker

**Comment by mgesing** [comment]
Resolved.
