### ISSUE TITLE
Different price for product after submiting an order

### ISSUE THREAD

**Issue by SalehGladius** [smartstoreag/SmartStoreNET#1372]
Before shopping, for example, price of iPhone Plus in store is $978:
![1](https://user-images.githubusercontent.com/8124646/36140928-3e8607f4-10b8-11e8-94a5-0664c9ac8a24.PNG)

but after buying it, in User Profile > Orders page, price is $1237:
![2](https://user-images.githubusercontent.com/8124646/36140936-44afbb2a-10b8-11e8-82a6-8dcc209d84b5.PNG)

is this a bug?

**Comment by mgesing** [comment]
On the detail pages you can see many different prices for a product. One reason for this is shown in the screenshot: attribute markups. The price on the order side is the price actually paid by the customer. This can be completely different if, for example, the product price has changed. So this is not a bug.
