### ISSUE TITLE
All payment Options are not Shown

### ISSUE THREAD

**Issue by FarrukhRB** [smartstoreag/SmartStoreNET#1374]
Hi,

        I've installed Offline and Paypal payment methods in my Store, but on frontEnd it only shows Paypal Methods, no offline Payment methods are shown.

Please help me in this. 
(Screen Shots attached for assistance).

Regards 
Farrukh
![adminpanel](https://user-images.githubusercontent.com/5442605/36376647-a5043852-1595-11e8-9fc4-d5be45075166.png)
![clientend](https://user-images.githubusercontent.com/5442605/36376648-a538a862-1595-11e8-83ec-8e4128549685.png)

**Comment by Michael-Herzog** [comment]
Hi,

what your see is rendered by PayPal Plus which eliminates all other payment options. 
Every PayPal-Method has different features. You should only activate one of them.

Regards

**Comment by mgesing** [comment]
You can include additional payment methods in the PayPal payment wall through "More payment methods" option on the PayPal PLUS configuration page.

**Comment by FarrukhRB** [comment]
Thanks for the help.
