### ISSUE TITLE
Not having access to defining a new type in SEO Names of plugin

### ISSUE THREAD

**Issue by pineportal** [smartstoreag/SmartStoreNET#1376]
I want to make a link short
But I do not have access to add it from the plugin to the following section

![new bitmap image](https://user-images.githubusercontent.com/31403448/36583349-96d21324-188a-11e8-8db1-cd2ebe8ed876.jpg)

**Comment by muratcakir** [comment]
What does _make link short_ mean? What exactly are you trying to accomplish? Please more info.

**Comment by pineportal** [comment]
I want to create a short link to share social networks
Like site https://goo.gl/
But with the domain of the site
http://mydomin.com/a1cd
And keep statistics of each of the clips and hits of various social networks
Now with the plugin I can create the address as below .
http://mydomin.com/short/a1cd
But I want to be this way
http://mydomin.com/a1cd
I can not use root.

**Comment by pineportal** [comment]
Automatically shared

![dddddddddddddd](https://user-images.githubusercontent.com/31403448/36607185-2201cf48-18db-11e8-8a08-8612d6a67dd4.jpg)

**Comment by Michael-Herzog** [comment]
If I uderstood correctly you have to work with action filters on the actions you want to track (e.g. ProductDetails).  When the product detail page is called (form shortened link or full link doesn't matter) you analyze the refferer, update the stats (or not) and let it go it's way to the originally called action.

**Comment by pineportal** [comment]
This is also a way But A short link to the social network is smarter and more beautiful.
I can develop this section. But Work will be hard at work in future upgrades.
yes i cant work with action filters but This does not work for me.
Thanks to the excellent store
