### ISSUE TITLE
Discrepancies between moment.js and .NET Framework date handling

### ISSUE THREAD

**Issue by mahdi87gh** [smartstoreag/SmartStoreNET#1382]
Hi everyone. I have this problem when I change the site language to anything other than English, I can not save items which have CreatedOn and EditedOn fields. I get these errors:

- The field 'ایجاد شده در' must be a date.
- The field 'ویرایش شده در' must be a date.

What should I do?

**Comment by muratcakir** [comment]
You seem to have changed the language to arabic. `Other than English` does not quite fit here. Where is the language pack from? And what exactly is the language?

You should provide more details.

**Comment by mahdi87gh** [comment]
The language is Persian (fa-ir)

**Comment by pineportal** [comment]
datetime.chtml
Changing the format of history is solved by the following problem
![ddddd](https://user-images.githubusercontent.com/31403448/37873406-a24b8f1e-3031-11e8-8ca5-1b2252551fd8.jpg)
This problem is due to the server language format

**Comment by muratcakir** [comment]
Could you please have a look at _moment.js_ localization file for Persian, [fa.js](https://github.com/smartstoreag/SmartStoreNET/blob/3.x/src/Presentation/SmartStore.Web/Content/vendors/moment/locale/fa.js), and tell me whether the content is correct?

**Comment by muratcakir** [comment]
I fixed it, but unfortunately it's impossible to display native (arabic) digits in the date picker control. Although the date picker is capable of doing so, .NET Framework cannot parse string dates with native digits. We'd have to change the ModelBinder for this and implement very hackish code. 

We have decided against it. I hope it's ok :-)

**Comment by pineportal** [comment]
Thank you for solving the problem
Persian Calendar Is Jalali 
is beter moment.js for jalaali
https://github.com/jalaali/moment-jalaali/blob/master/build/moment-jalaali.js
or 
https://github.com/fingerpich/jalali-moment

and persian datetimePicer is 
https://github.com/beygi/bootstrap-persian-datetimepicker
or
https://github.com/Mds92/MD.BootstrapPersianDateTimePicker


and 
https://en.wikipedia.org/wiki/Jalali_calendar
