### ISSUE TITLE
Error Occurred after installing Mail Chimp Plugin

### ISSUE THREAD

**Issue by FarrukhRB** [smartstoreag/SmartStoreNET#1388]
Hi,
  this error occured when I installed Mailchimp plugin downloaded from Smartstore market place. Please help me to resolve this issue, or for immediate solution, guide me how to uninstall plugin as Admin panel is not loading due to this error. 

Please see attached screenshot for error
![error](https://user-images.githubusercontent.com/5442605/37715897-012f176c-2d3f-11e8-826a-2c50536f5140.png)

**Comment by mgesing** [comment]
What SmatStore.NET version do you use?

**Comment by FarrukhRB** [comment]
its 3.0.3.0

**Comment by Michael-Herzog** [comment]
Hi,

I assume you're working with the 3.x branch. Correct? If so, you need to include the source code of the plugin from the 3.x branch of [this repository](https://github.com/smartstoreag/extra-plugins) or you switch  to 3.0.x which is the last stable release (at this moment 3.0.3) inclusive hotfixes.

Regards

**Comment by FarrukhRB** [comment]
Thanks A lot For solution.
