### ISSUE TITLE
Quantity doesn't reflect when Add to Cart

### ISSUE THREAD

**Issue by DragonZelda** [smartstoreag/SmartStoreNET#1393]
On product details page, press increase + or decrease - of the quantity box it will disappear and force the user to key in quantity value. After key in the number and press Add to Cart, the cart will always show quantity one.

**Comment by Michael-Herzog** [comment]
This problem is already fixed. Please pull the latest code.

**Comment by DragonZelda** [comment]
I pull the latest code. 
I find out that if I clean the solution and rebuild, this error will appear again.
