### ISSUE TITLE
RTL: catmenu active item in left

### ISSUE THREAD

**Issue by pineportal** [smartstoreag/SmartStoreNET#1405]
![2018-04-05 1](https://user-images.githubusercontent.com/31403448/38348410-cb601126-38b6-11e8-915e-0ac2fa3700c7.png)

**Comment by Michael-Herzog** [comment]
Thanks for reporting!

**Comment by SalehGladius** [comment]
In small displays, this mistake is already exist!

![image](https://user-images.githubusercontent.com/8124646/38636330-19429ae6-3ddd-11e8-8529-d62572486651.png)

**Comment by Michael-Herzog** [comment]
I cannot reproduce this anymore. Perhaps the old css declarations were cached on your testing device. Please try it on another device.
