### ISSUE TITLE
Payment & shipping options by customer roles

### ISSUE THREAD

**Issue by muratcakir** [smartstoreag/SmartStoreNET#141]
I'd like to see different payment options available by Customer Roles. It would allow you to only accept credit cards from your online customer base, but give an admin the ability to collect cash in person. This would allow one to use the system in a tradeshow
 type of setting where you have a cashier placing orders and accepting cash on behalf of patrons there in person.

You'd like the same thing for shipping so you wouldn't have to charge them shipping costs for an in person sale.

> Migrated from CodePlex: [Issue #136](https://smartstore.codeplex.com/workitem/136) from [canadiancubing](https://www.codeplex.com/site/users/view/canadiancubing), on 10/24/2013 5:01:57 PM

**Comment by mgesing** [comment]
[Resolved](https://github.com/smartstoreag/SmartStoreNET/commit/7fa48e659fc1a8fd4001d3fd0cc8347ceccffd0d)
