### ISSUE TITLE
The role of the admin can not remove the admin role

### ISSUE THREAD

**Issue by pineportal** [smartstoreag/SmartStoreNET#1412]

**Comment by mgesing** [comment]
The admin role is a system role defined by the shop system. System roles cannot be removed. Nobody would be able to enter the backend and administrate the shop.

**Comment by pineportal** [comment]
No. roll in user.
When there is a user with the admin role in the shop.
Can not erase the role of admin.
![2018-04-09 1](https://user-images.githubusercontent.com/31403448/38485045-bde46486-3bed-11e8-9a46-2b31c30cf4b5.png)
