### ISSUE TITLE
The role in user of the administrator can not remove

### ISSUE THREAD

**Issue by pineportal** [smartstoreag/SmartStoreNET#1413]
When there is a user with the admin role in the shop.
Can not remove the role of admin.
Disable role or cant not remove own role ;
![2018-04-09 1](https://user-images.githubusercontent.com/31403448/38485080-e0b516d6-3bed-11e8-951e-822c65213242.png)
When he remove his own role, can not login in the admin

**Comment by pineportal** [comment]
yes.
When one user is role admin, and remove role administrator, cant access in dashboard

**Comment by Michael-Herzog** [comment]
If multiple admins are active this is a totally proper behaviour. If the only admin of a store has locked himself out he has to go into the database to restore his access.
