### ISSUE TITLE
CMS Topic "Disclaimer" contains content for "Widerrufsrecht" in language "de"

### ISSUE THREAD

**Issue by iherwald** [smartstoreag/SmartStoreNET#1416]
```
				new Topic
					{
						SystemName = "Disclaimer",
						IncludeInSitemap = false,
						IsPasswordProtected = false,
						Title = "Disclaimer",
						Body = "<p>Put your disclaimer information here. You can edit this in the admin site.</p>"
					},
```
 ```
               .Alter("Disclaimer", x =>
                {
                    x.Title = "Widerrufsrecht";
                    x.Body = "<p>Fügen Sie Ihr Widerrufsrecht hier ein. Sie können diese in der Admin-Seite zu bearbeiten.</p>";
                })	

```

Maybe it would be better to introduce a new topic for "right of revocation".

**Comment by Michael-Herzog** [comment]
Sorry, I don't understand this issue. Have you installed SmartStore.NET in English and the topic was added in German?

**Comment by iherwald** [comment]
The (new) installation of SmartStore.NET is in German and it is technically OK.

I think it is a matter of translation (en <-> de):
The topic "Disclaimer" should reference to the content for "Haftungsausschluss" (German) and not to the content for "Widerrufsrecht" (German). The English content is OK here.

I would suggest to add a new topic like "RightOfRevocation" to the default installation, which should reference to the content for "Widerrufsrecht" (German). The English content could be "Right of revocation"

Of cource, a shop-admin could do this changes by himself. However, firstly this is quite confusing when you start a new shop project with German language.

**Comment by Michael-Herzog** [comment]
As I've never heard of any confusion about this matter (and we have a lot of german users) I'll close this issue. 

Thx
