### ISSUE TITLE
missing resource Admin.Configuration.Settings.Payment.CapturePaymentReason

### ISSUE THREAD

**Issue by pineportal** [smartstoreag/SmartStoreNET#1418]

**Comment by mgesing** [comment]
It's included [through](https://github.com/smartstoreag/SmartStoreNET/blob/3.x/src/Libraries/SmartStore.Data/Migrations/MigrationsConfiguration.cs#L292) this migration. Can't tell you why you don't have it. I looked it up in some test shops and it's available there.
