### ISSUE TITLE
database migration

### ISSUE THREAD

**Issue by wangleigpt** [smartstoreag/SmartStoreNET#1426]
i've added a new entity in ‘smartstore.data.domain’ and a mapper for it in ’smartstore.data.mapping‘, when i migrate the database using "enable-migration -force; add-migration xxx; update-database xxx;" in the Package Manager Console, it did nothing. thanks for any replys!

**Comment by mgesing** [comment]
The domain model is in SmartStore.Core.Domain, not SmartStore.Data.Domain. Before executing add-migration, did you select SmartStore.Data as the default project? Documentation is [here](http://docs.smartstore.com/display/SMNET30/Entity+Framework+Migrations).

**Comment by wangleigpt** [comment]
yes, it's in SmartStore.Core.Domain and i have selected SmartStore.Data as the defualt project. when running enable-migrations -force in pmc, it replys "Checking if the context targets an existing database... Code First Migrations enabled for project SmartStore.Data.", but when running add-migration MyMigration, the pmc replys "More than one migrations configuration type was found in the assembly 'SmartStore.Data'. Specify the name of the one to use." and nothing was added to the SmartStore.Data project.

**Comment by mgesing** [comment]
Never got this. Never executed enable-migrations -force, just add-migration. [Looks](http://www.mortenanderson.net/code-first-migrations-for-entity-framework) like it overwrites all existing migration configuration.

**Comment by wangleigpt** [comment]
Finnally, when added "--ConfigurationTypeName SmartStore.Data.Migrations.Configuration" to the commands, it worked!  thanks a lot!
