### ISSUE TITLE
Attribute selection on product does not work

### ISSUE THREAD

**Issue by Zengage** [smartstoreag/SmartStoreNET#1448]
![image](https://user-images.githubusercontent.com/9194241/40112142-5b7319e8-5905-11e8-9485-db423d7e7fe8.png)

I added a new attribute but I cannot select it on the product.
I have installed the latest 3.1.x branch.
It is also not working on the demo website 

![image](https://user-images.githubusercontent.com/9194241/40112235-9cd44f2e-5905-11e8-84d8-65b9303c6fa0.png)

**Comment by Zengage** [comment]
OK, it seems to be a browser issue. 
Drop-downs seem generally not to work in Firefox

**Comment by mgesing** [comment]
I cannot reproduce that. Works for me in Firefox.

![demo-backend](https://user-images.githubusercontent.com/8446701/40120014-740fa0ac-591e-11e8-8176-d27413e43e05.png)
