### ISSUE TITLE
Checkout Confirm Error

### ISSUE THREAD

**Issue by rzpatel** [smartstoreag/SmartStoreNET#1457]
During check keep receiving the following error:
14.6667 is not a valid value for Int32.
and the cart is cleared.

SS v 3.1, PayPal Standard v 3.1

**Comment by Michael-Herzog** [comment]
This was fixed for SmartStore.NET 3.1.5 or the current dev branch. You can also check your message templates for this value if you don't wnat to pull the latest code.
