### ISSUE TITLE
Plugins: Upload picture in configure page

### ISSUE THREAD

**Issue by SalehGladius** [smartstoreag/SmartStoreNET#1473]
Hi, 
I've wrote a plugin that need a picture uploader in configuration page, but the uploader doesn't display correctly! It's rendered as number field!

**Comment by mgesing** [comment]
Decorate your view model property with attribute UIHint("Picture"). See [here](https://github.com/smartstoreag/SmartStoreNET/blob/3.x/src/Plugins/SmartStore.OfflinePayment/Models/ConfigurationModel.cs#L25) and [here](https://github.com/smartstoreag/SmartStoreNET/blob/3.x/src/Plugins/SmartStore.OfflinePayment/Views/OfflinePayment/GenericConfigure.cshtml#L34).
