### ISSUE TITLE
Having a license type product

### ISSUE THREAD

**Issue by Cloze** [smartstoreag/SmartStoreNET#1480]
Hi,

how can I have a product like "Steam wallet".

I mean you buy 10 codes from the valve and want to sell it in your website. you should put all those 10 codes somewhere and when user buy the product you show the license to them.

is it even possible ?

**Comment by muratcakir** [comment]
No, not out-the-box.  Can be implemented as plugin though.

**Comment by Cloze** [comment]
can you explain more please ?
where should I start? and what should I start with ?
