### ISSUE TITLE
Re-enable saving settings as JSON

### ISSUE THREAD

**Issue by iherwald** [smartstoreag/SmartStoreNET#1489]
Please, re-enable SaveSettingsJson (line 375 and 376) in SmartStore.Services.Configuration.SettingService:

		protected virtual void SaveSettingCore(ISettings settings, int storeId = 0)
		{
			Guard.NotNull(settings, nameof(settings));

			using (BeginScope())
			{
				var settingType = settings.GetType();
				var prefix = settingType.Name;

				if (settingType.HasAttribute<JsonPersistAttribute>(true))
				{
					SaveSettingsJson(settings);
					return;
				}

**Comment by muratcakir** [comment]
Resolved. Forgot to tag the commit message.
