### ISSUE TITLE
error while uninstalling plugins

### ISSUE THREAD

**Issue by AlfVat** [smartstoreag/SmartStoreNET#1496]
Hi.
i cloned this solution on my pc and rebuild all projects as suggested in manual.
everything was ok. but in admin panel when i selected all plugins for uninstalling i got this error:

> System.Data.SqlClient.SqlException: 'Invalid column name 'CreatedOn'.'
in this line:
`var result = _command.ExecuteReader(behavior);`
in CachingCommand.cs line 169.

**Comment by muratcakir** [comment]
This occurs only in debug mode and is absolutely harmless. Just ignore it and continue. Unfortunately, EF throws an exception internally to check for features and there's no workaround for it.
