### ISSUE TITLE
Error Installing MegaSearch Plugin

### ISSUE THREAD

**Issue by sujanvaland** [smartstoreag/SmartStoreNET#1509]
Null Value error while installing MegaSearch Plugin, when debug descriptor show below message
Error loading plugin 'SmartStore.MegaSearch' Method 'Highlight' in type 'SmartStore.MegaSearch.Lucene.LuceneSearchEngine'
![smartstore](https://user-images.githubusercontent.com/7682725/46005423-ddb39880-c0d2-11e8-8bf0-c489392a4c4f.png)

**Comment by mgesing** [comment]
Your MegaSearch plugin version is incompatible with your shop version.

You are probably trying to run the MegaSearch Plugin 3.1.5 with the latest code from Branch 3.x. 3.x is the current developer branch, means under development. There are no plugins published for a developer branch.

**Comment by sujanvaland** [comment]
Thankyou so much for the quick response, Appreciated but developed whole
portal with this branch can you help me install the same plugin in 3.x
plzzzz
