### ISSUE TITLE
Add Manufacturer without uploading image.

### ISSUE THREAD

**Issue by horseyhorsey** [smartstoreag/SmartStoreNET#1517]
3.x
SQLCE. 

Trace:
    Controller: Manufacturer, Action: Create

    An error occurred while updating the entries. See the inner exception for details.

    A foreign key value cannot be inserted because a corresponding primary key value does not exist. [ Foreign key constraint name = FK_dbo.Manufacturer_dbo.Picture_PictureId ]

**Comment by mgesing** [comment]
Duplicate #1493. Errors have the same reason.
