### ISSUE TITLE
Allow for Blank Salutation & Country

### ISSUE THREAD

**Issue by CompleteCoders** [smartstoreag/SmartStoreNET#1518]
In the General Settings -> Company tab the user should not be forced to enter a Salutation or Country if they do not want to.  The user should be allowed to leave these blank.

This is problematic for a client who doesn't want to add a Mr/Mrs to the order form print screen or the email templates.  Same if they don't want to add their country.

**Comment by muratcakir** [comment]
Can be configured in Configuration > General > Customer settings.

**Comment by CompleteCoders** [comment]
I have moved this to a post in the forum because I must be doing something else wrong:

http://community.smartstore.com/index.php?app=forums&module=post&section=post&do=new_post&f=86
