### ISSUE TITLE
Admin: Cannot view or Create Attribute combinations

### ISSUE THREAD

**Issue by horseyhorsey** [smartstoreag/SmartStoreNET#1519]
System.Data.SqlServerCe.SqlCeException: 'The ntext and image data types cannot be used in WHERE, HAVING, GROUP BY, ON, or IN clauses, except when these data types are used with the LIKE or IS NULL predicates.'

**ProductController.ProductVariantAttributeCombinationList - 3690**

**Comment by mgesing** [comment]
Probably fixed by 512fd4c993bbab113dff3b525882c78a97813b79

**Comment by horseyhorsey** [comment]
Confiming fixed, thanks.
