### ISSUE TITLE
 Show all products from all stores in just one page

### ISSUE THREAD

**Issue by Razart007** [smartstoreag/SmartStoreNET#1536]
Is it possible to show all products from all stores in just one page? I did not find the setting to do this. Do I need to install any plugins?

**Comment by Razart007** [comment]
In this case it would be to integrate the sub-stores in only one

**Comment by muratcakir** [comment]
Please refer to our [forum](http://community.smartstore.com/) for support related stuff in the future.

But no, it is not possible out-of-the-box without coding.
