### ISSUE TITLE
How to add new tab for blogPost or newsItem edit page in admin panel?

### ISSUE THREAD

**Issue by SalehGladius** [smartstoreag/SmartStoreNET#1538]
When I cast `BlogPostModel` or `NewsItemModel` to `TabbableModel`, It throws an error that unable to cast! so I should handle it separately!

I think it will be solved by adding `TabbaleModel` to those mentioned Models!

     public class NewsItemModel : TabbableModel, EntityModelBase, IStoreSelector

**Comment by mgesing** [comment]
For BlogPostModel see #1507. NewsItemModel to be done...
