### ISSUE TITLE
FlexBlue theme references wrong variables

### ISSUE THREAD

**Issue by prakashkborntowin** [smartstoreag/SmartStoreNET#1547]
While am select Flex-blue theme it shows error.refer screen shot
![themeissue](https://user-images.githubusercontent.com/45592659/49628957-01695800-fa0d-11e8-91fb-9469dbe0a450.png)

**Comment by muratcakir** [comment]
Can you please post the inner exception?

**Comment by prakashkborntowin** [comment]
![image](https://user-images.githubusercontent.com/45592659/50071918-66853080-01f9-11e9-8543-6fa17578a467.png)
