### ISSUE TITLE
Security: Everyone can access to plugin's core files (*.dll)

### ISSUE THREAD

**Issue by SalehGladius** [smartstoreag/SmartStoreNET#1550]
If someone uses this format of url, can download the plugin's core files!

http://yourdomain.com/plugins/yourpluginname/yourpluginname.dll

[Test link!](http://demo.smartstore.com/backend/Plugins/SmartStore.MegaSearch/SmartStore.MegaSearch.dll)

Is this normal?

**Comment by muratcakir** [comment]
Resolved by eadd573
