### ISSUE TITLE
Issue when creating nupkg from plugin from version 3.1.5

### ISSUE THREAD

**Issue by rnabati** [smartstoreag/SmartStoreNET#1558]
hi guys,
When i creating nupkg from smartstore plugin, i got this error:
 cannot create a package that has no dependencies nor content.

![1111](https://user-images.githubusercontent.com/1849372/50377360-2b3b9500-0631-11e9-98e9-c61fde9ed6d7.JPG)

there is a same issue that raised on [Link](https://github.com/smartstoreag/SmartStoreNET/issues/644)
on 3 years ago but it seems this exists on version 3.1.5.

**Comment by pineportal** [comment]
root path chenge  
src\Presentation\SmartStore.Web\

**Comment by rnabati** [comment]
@pineportal It does not matter. In both cases, the same error is observed
![2222](https://user-images.githubusercontent.com/1849372/50380937-248f3b00-068e-11e9-976d-8896658cc969.JPG)

**Comment by mgesing** [comment]
The root path is wrong. It must be the build folder, in your case probably D:\_SMARTSTORE\build\Web
