### ISSUE TITLE
Installation failes. Error at stage: PopulateLocaleResources (Value must not be NULL. Parameter: httpContext)

### ISSUE THREAD

**Issue by iherwald** [smartstoreag/SmartStoreNET#1568]
Installation fails with current branch 3.x and empty database (settings.txt not provided).

Error message on install page:
`Installation schlug fehl: An error occurred during installation. Stage: PopulateLocaleResources (Der Wert darf nicht NULL sein. Parametername: httpContext)`

![image](https://user-images.githubusercontent.com/3755359/51127794-af46fe00-1826-11e9-8039-1c9ae2ceccb6.png)

![image](https://user-images.githubusercontent.com/3755359/51127842-ce459000-1826-11e9-8362-8ab3ac72b5ae.png)

![2019-01-14 17_53_37-smartstorenet running - microsoft visual studio](https://user-images.githubusercontent.com/3755359/51127688-6131fa80-1826-11e9-8acf-7e3d1573ebb6.png)

**Comment by EDUARDOMBRAGA** [comment]
@iherwald 
Did you get any solutions?
I'm making the same mistake.

**Comment by Michael-Herzog** [comment]
This looks like it's caused by my commit:
https://github.com/smartstoreag/SmartStoreNET/commit/034ec4e04fd127bddb34e5a6f462344883937610

I'll fix it tomorrow!

**Comment by EDUARDOMBRAGA** [comment]
@Michael-Herzog 
I am grateful, I await correction.
