### ISSUE TITLE
Structured data: Google complains about missing price element

### ISSUE THREAD

**Issue by pineportal** [smartstoreag/SmartStoreNET#1579]

**Comment by pineportal** [comment]
![screenshot_6](https://user-images.githubusercontent.com/31403448/53716746-25e99a80-3e6b-11e9-84df-e9e3904f44df.jpg)

**Comment by pineportal** [comment]
remove 
`itemprop="offers" itemscope itemtype="http://schema.org/Offer"`
in call for price fix error


![new bitmap image](https://user-images.githubusercontent.com/31403448/53729119-a15a4480-3e89-11e9-9688-051c7846b0e6.jpg)

**Comment by CNA1823** [comment]
You made my day man. This problem was my night mare.
