### ISSUE TITLE
Product Detail Manufacturer mapping

### ISSUE THREAD

**Issue by rzpatel** [smartstoreag/SmartStoreNET#1597]
If a product is mapped to multiple manufacturers, only one manufacturer is displayed on the product page. Is this by design or a bug since display order is specified.

**Comment by muratcakir** [comment]
It is by design. Multiple manufacturers per product is a legacy feature and will be removed from source somewhere in the future.

**Comment by AbdonDeKousemaeker** [comment]
Please don’t remove this feature.!
We use it very often, great option.

Met vriendelijke groet, Best regards, Mit freundlichen Grüßen, Cordialement
KOOMBA b.v.

Abdon De Kousemaeker
Mobile: +31 612 8380 12
E-mail: abdon@koomba.eu
Postadres:
Postbus 1632
3260 BC  OUD-BEIJERLAND

Tel:  +31 10 204 55 25
Fax: +31 10 204 55 55

Brainpark II Rotterdam
Lichtenauerlaan 102
3062 ME  ROTTERDAM
www.koomba.eu

**Comment by rzpatel** [comment]
Yes, I would agree. Please do not remove this feature as it is a great option and can be very helpful in certain scenarios.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by muratcakir** [comment]
OK, we won't remove it from source :-), but won't display multiple brands in storefront either.

**Comment by rzpatel** [comment]
Thank You for your consideration.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
