### ISSUE TITLE
Product attributes not appear on front-end and showing the validation error.

### ISSUE THREAD

**Issue by hpatel4u** [smartstoreag/SmartStoreNET#1603]
HI,

I have edited the product and added the attributes COLOR & LENGTH.

![image](https://user-images.githubusercontent.com/9670359/55210319-d2b9fc00-520c-11e9-8035-db4aaf39ffad.png)

The same is not reflecting on front-end but showing validation message and i could not continued adding product to the cart.

![image](https://user-images.githubusercontent.com/9670359/55210374-0137d700-520d-11e9-98eb-65db5dd8279f.png)
 
am i doing something wrong in setup or what?

Regards,
Hi Ten

**Comment by mgesing** [comment]
The first screenshot shows no value for color and length. Click "Edit options" to specify values for these attributes, as they are also marked as required.
