### ISSUE TITLE
SmartStore.Services.Seo.SeoExtensions

### ISSUE THREAD

**Issue by muratcakir** [smartstoreag/SmartStoreNET#206]
The Getname method can change like the following?
<pre><code>public static string GetSeName(string name, bool convertNonWesternChars, bool llowUnicodeCharsInUrls)
        {
            if (String.IsNullOrEmpty(name))
                return name;
            string okChars = "abcdefghijklmnopqrstuvwxyz1234567890 _-";
            name = name.Trim().ToLowerInvariant();

            if (convertNonWesternChars)
            {
                if (_seoCharacterTable == null)
                    InitializeSeoCharacterTable();
            }

            var sb = new StringBuilder();
            foreach (char c in name.ToCharArray())
            {
                string c2 = c.ToString();
                if (convertNonWesternChars)
                {
                    if (_seoCharacterTable.ContainsKey(c2))
                        c2 = _seoCharacterTable[c2];
                }

                // codehint: sm-edit
                //if (allowUnicodeCharsInUrls)
                //{
                //  if (char.IsLetterOrDigit(c) || okChars.Contains(c2))
                //      sb.Append(c2);
                //}
                //else if (okChars.Contains(c2))
                //{
                //  sb.Append(c2);
                //}
                switch (c2) {
                    case "ö":
                    case "Ö":
                        sb.Append("o"); break;
                    case "ü":
                    case "Ü":
                        sb.Append("u"); break;
                    case "ğ":
                    case "Ğ":
                        sb.Append("g"); break;
                    case "ı":
                    case "İ":
                        sb.Append("i"); break;
                    case "ş":
                    case "Ş":
                        sb.Append("s"); break;
                    case "ç":
                    case "Ç":
                        sb.Append("c"); break;

                    case "ä": sb.Append("ae"); break;                   
                    case "ß": sb.Append("ss"); break;
                    case "Ä": sb.Append("AE"); break;
                    case "é":
                    case "è":
                    case "ê": sb.Append('e'); break;
                    case "á":
                    case "à":
                    case "â": sb.Append('a'); break;
                    case "ú":
                    case "ù":
                    case "û": sb.Append('u'); break;
                    case "ó":
                    case "ò":
                    case "ô": sb.Append('o'); break;

                    default:
                        if (okChars.Contains(c2))
                            sb.Append(c2);
                        break;
                }   // switch
            }
            string name2 = sb.ToString();
            name2 = name2.Replace(" ", "-");
            while (name2.Contains("--"))
                name2 = name2.Replace("--", "-");
            while (name2.Contains("__"))
                name2 = name2.Replace("__", "_");
            return name2;
        }</code></pre>

> Migrated from CodePlex: [Issue #204](https://smartstore.codeplex.com/workitem/204) from [yazilim](https://www.codeplex.com/site/users/view/yazilim), on 12/8/2013 10:06:24 AM

**Comment by mgesing** [comment]
[Resolved.](https://github.com/smartstoreag/SmartStoreNET/commit/dcdc59130dc7954f9865253b949d7dff59ab0f60)
