### ISSUE TITLE
Add personalization to newsletter subscriptions

### ISSUE THREAD

**Issue by muratcakir** [smartstoreag/SmartStoreNET#214]
and of course unsubscriptions. A salutation would be sufficient but it seems the placeholder
<em>%Customer.FullName%</em> doesn't get replaced

> Migrated from CodePlex: [Issue #212](https://smartstore.codeplex.com/workitem/212) from [MichaelHerzog](https://www.codeplex.com/site/users/view/MichaelHerzog), on 12/11/2013 5:40:31 PM

**Comment by Michael-Herzog** [comment]
Won't work. Newslettersubscription only request the email address. We could get the customer by email but then we would have to parse the whole salutation into the token and in case there is no customer leave it empty.
