### ISSUE TITLE
"Did you mean" search feature

### ISSUE THREAD

**Issue by muratcakir** [smartstoreag/SmartStoreNET#272]
Hi Everyone, 
You have considered implementing "Did you mean" feature, I think this feature would set a big difference with nopCommerce. It is a very useful function, when people look for something

> Migrated from CodePlex: [Issue #270](https://smartstore.codeplex.com/workitem/270) from [andrew90s](https://www.codeplex.com/site/users/view/andrew90s), on 1/30/2014 4:16:19 PM

**Comment by mgesing** [comment]
Implemented by MegaSearch plugin.
