### ISSUE TITLE
Update to latest jquery version

### ISSUE THREAD

**Issue by muratcakir** [smartstoreag/SmartStoreNET#275]
self explaining

> Migrated from CodePlex: [Issue #273](https://smartstore.codeplex.com/workitem/273) from [muratcakir](https://www.codeplex.com/site/users/view/muratcakir), on 1/31/2014 2:59:18 PM

**Comment by coliff** [comment]
Can it be updated again to latest version? v2.2.2
REF: http://blog.jquery.com/2016/03/17/jquery-1-12-2-and-2-2-2-released/

**Comment by muratcakir** [comment]
We'd rather NOT do it now in the minor release 2.5.1, but in version 3. Also, jQuery 3 will surely have been released by then.

**Comment by muratcakir** [comment]
Related to #995
