### ISSUE TITLE
Implement FoxRate plugin

### ISSUE THREAD

**Issue by muratcakir** [smartstoreag/SmartStoreNET#310]
<a href="http://foxrate.de" rel="nofollow">http://foxrate.de</a>

> Migrated from CodePlex: [Issue #308](https://smartstore.codeplex.com/workitem/308) from [muratcakir](https://www.codeplex.com/site/users/view/muratcakir), on 3/24/2014 7:48:40 PM

**Comment by Michael-Herzog** [comment]
Foxrate seems to be dead
