### ISSUE TITLE
Make an option for default product list view style

### ISSUE THREAD

**Issue by muratcakir** [smartstoreag/SmartStoreNET#332]
Grid | List

> Migrated from CodePlex: [Issue #330](https://smartstore.codeplex.com/workitem/330) from [muratcakir](https://www.codeplex.com/site/users/view/muratcakir), on 4/16/2014 4:52:25 PM

**Comment by MichaelCsitkovics** [comment]
This Option doesn't work in 2.2.2. It is always displayed as grid.

**Comment by Michael-Herzog** [comment]
Just checked in current development branch (2.x) and our demostores (2.2.2.0). The option is being applied as expected.
