### ISSUE TITLE
Make payment logo in checkout configurable 

### ISSUE THREAD

**Issue by muratcakir** [smartstoreag/SmartStoreNET#347]
Suggestion from <a href="http://community.smartstore.com/index.php?/topic/45356-payment-info/#entry259841" rel="nofollow">
forum</a>. 
... or better, enable to upload a default image for each plugin.

> Migrated from CodePlex: [Issue #345](https://smartstore.codeplex.com/workitem/345) from [mgesing](https://www.codeplex.com/site/users/view/mgesing), on 4/19/2014 12:08:30 PM

**Comment by mgesing** [comment]
Resolved by #607.
