### ISSUE TITLE
Checkout: Validate and double enter customer email address

### ISSUE THREAD

**Issue by muratcakir** [smartstoreag/SmartStoreNET#450]
To reduce typing errors. See <a href="http://community.smartstore.com/index.php?/topic/46167-e-mail-adresse-best%C3%A4tigen/" rel="nofollow">
http://community.smartstore.com/index.php?/topic/46167-e-mail-adresse-best%C3%A4tigen/</a>

> Migrated from CodePlex: [Issue #448](https://smartstore.codeplex.com/workitem/448) from [mgesing](https://www.codeplex.com/site/users/view/mgesing), on 8/11/2014 9:08:39 AM

**Comment by Michael-Herzog** [comment]
Option was implemented by now
