### ISSUE TITLE
Localize MVC validation strings (see image)

### ISSUE THREAD

**Issue by mgesing** [smartstoreag/SmartStoreNET#557]
![image](https://cloud.githubusercontent.com/assets/8446701/5492162/5ae5918c-86df-11e4-97f3-f2d98be778f3.png)

**Comment by muratcakir** [comment]
Cannot find the res entry :-( It's a minor _bug_ anyway

**Comment by Fensterbank** [comment]
I think it's this: http://weblogs.asp.net/imranbaloch/localizing-default-error-messages-in-asp-net-mvc-and-web-form
