### ISSUE TITLE
Could not load file or assembly 'Microsoft.Data.Edm' or one of its dependencies.

### ISSUE THREAD

**Issue by milldol1984** [smartstoreag/SmartStoreNET#586]
Hi all, I've just downloaded the source code and build successfully. But when I run, I got the exception
"Could not load file or assembly 'Microsoft.Data.Edm' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"

I see the version of file in packages folder is 5.6.1.61768, but in project references is 5.6.1.0.
Any advices?
Thanks.
Nguyen Le.

**Comment by mgesing** [comment]
Try cleaning and rebuilding the solution. See [here](https://github.com/smartstoreag/SmartStoreNET/issues/440).
