### ISSUE TITLE
Minor view mode category fix

### ISSUE THREAD

**Issue by mehradi-github** [smartstoreag/SmartStoreNET#602]
controller:catalog, action:category
minor view mode fix: if(!String.IsNullOrEmpty(category.DefaultViewMode)) change => if (string.IsNullOrEmpty(command.ViewMode) && !String.IsNullOrEmpty(category.DefaultViewMode))

** please add me to Collaborators for push commites (user:mehradi-github),Thanks **

**Comment by muratcakir** [comment]
Thanks for contributing. Just fork the project and create pull requests. We will then pull your changes after a review.
