### ISSUE TITLE
important! varbinary(max) type and filesystem for picture table Not suitable( product's pictures )

### ISSUE THREAD

**Issue by mehradi-github** [smartstoreag/SmartStoreNET#623]
important! varbinary(max) type and filesystem for picture table Not suitable( product's pictures )
use : 
(FILESTREAM)    https://technet.microsoft.com/en-us/library/bb933993(v=sql.105).aspx
&
( FileTables)           https://msdn.microsoft.com/en-us/library/ff929144.aspx

**Comment by muratcakir** [comment]
No SQL CE support. The latter is new in SQL Server 2014.
