### ISSUE TITLE
Unable to add SQl server details while installing database

### ISSUE THREAD

**Issue by alpesh0063** [smartstoreag/SmartStoreNET#638]
Hello Sir,

After setting up IIS and ASP.Net version I'm facing issue while installing on browser.
![alps](https://cloud.githubusercontent.com/assets/11247466/6427170/b065e5e2-bf9e-11e4-897d-1586e33d888c.jpg)
![alps1](https://cloud.githubusercontent.com/assets/11247466/6427174/dbe9c698-bf9e-11e4-9e84-63aefeba9d28.jpg)

**Comment by Michael-Herzog** [comment]
When checking the second option (Use SQL Server) there has to open an extended input mask where you would have to enter the data the error message says it's missing. I've also checked with firefox but I can't reproduce this problem. Please try again with another browser.
