### ISSUE TITLE
Create plugin package problem

### ISSUE THREAD

**Issue by muhammetsahin** [smartstoreag/SmartStoreNET#644]
Hi,

I tried to create package but I get an error:
cannot create a package that has no dependencies nor content

![image](https://cloud.githubusercontent.com/assets/2045788/6541253/e369e5d0-c4ce-11e4-8780-f22cf61b5ad7.png)

**Comment by mgesing** [comment]
That has been [fixed](https://github.com/smartstoreag/SmartStoreNET/commit/a296d48014c58a9b13e858b92efa3d797459713f). Please try again with latest code.
