### ISSUE TITLE
WebApi Publishing Problem

### ISSUE THREAD

**Issue by barisfr** [smartstoreag/SmartStoreNET#653]
i tried publishing webapi but i get this result.
![webapipub](https://cloud.githubusercontent.com/assets/10867454/6673602/bcbdcab2-cc14-11e4-959c-cafdd82f169e.jpg)

after this problem i tried publish directement ftp and it s work . 
if you want publish WebApi , with ftp no problem.

**Comment by mgesing** [comment]
We do not publish a single plugin, so we never get in touch with this. See [how-to-build.txt](https://github.com/smartstoreag/SmartStoreNET/blob/2.x/how-to-build.txt).

If you want to fix it anyway, try one of the solutions mentioned [here](http://stackoverflow.com/questions/10989051/why-do-i-get-the-error-the-target-gatherallfilestopublish-does-not-exist).
