### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by firatoltulu** [smartstoreag/SmartStoreNET#659]
Today dowload smartstore from http://www.smartstore.com and installed my server.
i have a error to adding product.

Entity validation failed
Entity Name: Product - Id: Product - State: 0
Property: Name Error: The Name field is required.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Data.Entity.Validation.DbEntityValidationException: Entity validation failed
Entity Name: Product - Id: Product - State: 0
Property: Name Error: The Name field is required.

What i do?

**Comment by mgesing** [comment]
Specify a name for the product.

**Comment by firatoltulu** [comment]
I know and i do Specify 
![adsiz](https://cloud.githubusercontent.com/assets/4473771/6764688/2973ddd6-cfc6-11e4-8d45-ba334053a4be.png)
a name for product

**Comment by mgesing** [comment]
Are there more infos in System > Log for this error message (stack trace)?
Do you meet the [system requirements](https://github.com/smartstoreag/SmartStoreNET/wiki/system-requirements), most notably IIS 7+?

**Comment by firatoltulu** [comment]
Hi,

[DbEntityValidationException: Entity validation failed
Entity Name: Product - Id: Product - State: 0
	Property: Name Error: The Name field is required.
]
   SmartStore.Data.ObjectContextBase.PerformPreSaveActions(IList`1& modifiedEntries, HookedEntityEntry[]& modifiedHookEntries) +1341
   SmartStore.Data.ObjectContextBase.SaveChanges() +45
   SmartStore.Services.Catalog.ProductService.InsertProduct(Product product) +56
   SmartStore.Admin.Controllers.ProductController.Create(ProductModel model, Boolean continueEditing, FormCollection form) +492
   lambda_method(Closure , ControllerBase , Object[] ) +229
   System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +242
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +39
   System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) +12
   System.Web.Mvc.Async.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) +139
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +112
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +452
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +452
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +452
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +452
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +452
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +452
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +452
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +452
   System.Web.Mvc.Async.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) +15
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +37
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +241
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +29
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +111
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +53
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +19
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +51
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +111
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +606
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +288

**Comment by firatoltulu** [comment]
Hi,
IIS version is 7.5 and windows 2008 r2

**Comment by zihniartar** [comment]
Hello Firat,

we have fixed that issue in https://github.com/smartstoreag/SmartStoreNET/commit/72e6060da8831a3fabe3de1d6d89dbca8671010f

and

https://github.com/smartstoreag/SmartStoreNET/commit/7ac0681539f5e1dd38d0bd79f1402d20a18f1d5c


regards,

Zihni

**Comment by firatoltulu** [comment]
Hello Zihni,

Thanks.

On Mon, Mar 23, 2015 at 10:11 AM, zihniartar <notifications@github.com>
wrote:

> Hello Firat,
>
> we have fixed that issue in 72e6060
> <https://github.com/smartstoreag/SmartStoreNET/commit/72e6060da8831a3fabe3de1d6d89dbca8671010f>
>
> and
>
> 7ac0681
> <https://github.com/smartstoreag/SmartStoreNET/commit/7ac0681539f5e1dd38d0bd79f1402d20a18f1d5c>
>
> regards,
>
> Zihni
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smartstoreag/SmartStoreNET/issues/659#issuecomment-84875911>
> .
>



-- 
Saygılarımla.
İyi Çalışmalar.
------------------------------
Fırat Oltulu
*Solution Architect*
