### ISSUE TITLE
An exception on product copy

### ISSUE THREAD

**Issue by andriisydor** [smartstoreag/SmartStoreNET#664]
Error
An error occurred while updating the entries. See the inner exception for details.

Some time it works, but sometimes it fails... so the copy appears with a lot of field missing

maybe it could help, we use standard and 3 more languages... log does NOT show any error or exception

**Comment by andriisydor** [comment]
So i deleted one language and it copies well

**Comment by Michael-Herzog** [comment]
Can you transmit the language you've deleted to me so I can try to reproduce this error?

**Comment by andriisydor** [comment]
Ukrainian, UA

**Comment by andriisydor** [comment]
Should be any try/catch with logging in CopyProductService?

**Comment by andriisydor** [comment]
Should be any try/catch with logging in CopyProductService?

**Comment by andriisydor** [comment]
little more details:
"Cannot insert duplicate key row in object 'dbo.UrlRecord' with unique index 'IX_UrlRecord_Slug'. The duplicate key value is (-always-ultra-platinum-super-plus).\r\nThe statement has been terminated."

on CopyProductService:
 _urlRecordService.SaveSlug(productCopy, productCopy.ValidateSeName("", name, false), lang.Id);

**Comment by muratcakir** [comment]
Fixed in V2.2
