### ISSUE TITLE
Restrict payment methods to certain countries.

### ISSUE THREAD

**Issue by muratcakir** [smartstoreag/SmartStoreNET#67]
Example: CashOnDelivery only possible in Germany.

> Migrated from CodePlex: [Issue #57](https://smartstore.codeplex.com/workitem/57) from [WolfgangSchmerge](https://www.codeplex.com/site/users/view/WolfgangSchmerge), on 8/12/2013 11:47:20 AM

**Comment by mgesing** [comment]
[Resolved](https://github.com/smartstoreag/SmartStoreNET/commit/7fa48e659fc1a8fd4001d3fd0cc8347ceccffd0d)
