### ISSUE TITLE
During the output text content of processed asset an unknown error has occurred. See more details: Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by Kaushik1987** [smartstoreag/SmartStoreNET#679]
![untitled](https://cloud.githubusercontent.com/assets/11991900/7250272/5bc0af68-e83e-11e4-8f7d-7760504c1bc4.png)
I have download the Latest version of this application and it's up and running under my visual studio. But when I moved to local IIS 8.5 its not loading CSS. I have checked and found that .less is being not render . Under Firebug it's give me following Error  : "NetworkError: 500 Internal Server Error - http://localhost/Content/install/install.less"   

I have checked and found that file exist on published version of IIS.

**Comment by mgesing** [comment]
Sounds like the less handler is not configured.
![less-handler](https://cloud.githubusercontent.com/assets/8446701/7254664/d906e702-e844-11e4-925e-2d861932127d.png)

**Comment by Kaushik1987** [comment]
Thx for your replay, 

The configuration was correct and with all mime type & handler. 

The actual issue was that the released application required ClearScript.V8 Dll, I have copy paste all dll under bin folder bat later on i came to know that It has to be Under Bin\ ClearScript.V8\  .

thanks for your replay.
