### ISSUE TITLE
accessviolationexception in SmartStore.Licensing AutoMapping error

### ISSUE THREAD

**Issue by andriisydor** [smartstoreag/SmartStoreNET#681]
в System.Runtime.CompilerServices.RuntimeHelpers._CompileMethod(IRuntimeMethodInfo method)
   в System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType, Object target)
   в System.Linq.Expressions.Compiler.LambdaCompiler.CreateDelegate()
   в System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda, DebugInfoGenerator debugInfoGenerator)
   в System.Linq.Expressions.Expression`1.Compile()
   в AutoMapper.DelegateFactory.CreateGet(PropertyInfo property)
   в AutoMapper.Impl.PropertyGetter..ctor(PropertyInfo propertyInfo)
   в AutoMapper.Impl.PropertyAccessor..ctor(PropertyInfo propertyInfo)
   в AutoMapper.Impl.ReflectionHelper.ToMemberAccessor(MemberInfo accessorCandidate)
   в AutoMapper.MappingExpression`2.ForMember(Expression`1 destinationMember, Action`1 memberOptions)
   в SmartStore.Admin.Infrastructure.AutoMapperStartupTask.Execute() в d:\Development\STORE\SmartStore.NET 2.2.0\SmartStoreNET-2.2.0\SmartStoreNET-2.2.0\src\Presentation\SmartStore.Web\Administration\Infrastructure\AutoMapperStartupTask.cs

in fires on Mapper.CreateMap<PluginDescriptor, PluginModel>() in AutoMapperStartupTask.cs

to reproduce it unit-testing for SmartStore.Web.MVC.Tests is enough

**Comment by muratcakir** [comment]
All unit tests pass succesfully, especially this one. I need more info about when this happens, and in which environment (OS, IIS version etc.)

**Comment by andriisydor** [comment]
it happens in case of using SmartStoreNET.Web.2.2.0.zip unpack, install and here we go it fails with exception
i've run Source code (zip) successfully few time in debug mode

**Comment by andriisydor** [comment]
![](http://i.imgur.com/KdRdGWu.png)

**Comment by andriisydor** [comment]
When i unpack the solution what i have, just haven't an access

**Comment by pungggi** [comment]
I downloaded todaz and have the same problem, i do not unterstand what was the solution?

**Comment by mgesing** [comment]
[SmartStore.Licensing.dll](https://github.com/smartstoreag/SmartStoreNET/blob/2.x/lib/SmartStore.Licensing/SmartStore.Licensing.dll) was updated to solve the problem, so simply update this DLL (click "Raw").

**Comment by pungggi** [comment]
I did that, delete the reference and loaded the new from that dll, and the namespace is still missing... what am i doing wrong..?

**Comment by mgesing** [comment]
Move it the SmartStore.Licensing subfolder and copy it in \src\Presentation\SmartStore.Web\bin folder.

**Comment by pungggi** [comment]
nope no affect..

**Comment by mgesing** [comment]
Maybe the app loads the old version from the temporary ASP.NET files folder. What is the exact exception message you get? Is it the same as in the first post above?
