### ISSUE TITLE
Content Slider slides should be Language independent not culture independent?

### ISSUE THREAD

**Issue by Sherif-Ahmed** [smartstoreag/SmartStoreNET#682]
I found that you are in the HomeController -> ContentSlider

```
        var slides = settings.Slides
            .Where(s => 
                s.LanguageCulture == _services.WorkContext.WorkingLanguage.LanguageCulture && 
                (!s.LimitedToStores || (s.SelectedStoreIds != null && s.SelectedStoreIds.Contains(_services.StoreContext.CurrentStore.Id)))
            )
            .OrderBy(s => s.DisplayOrder);
```

so if I defined two Language with the same culture if will get the same slides ...

I think it should depend on the Language which i defined in the settings... 
Thanks in advanced ... 
If you mean that it must be culture independent please ignore this.

**Comment by muratcakir** [comment]
The question is: why would you have two languages with the exact same culture? One language with many cultures makes sense though. Am I missing something?
