### ISSUE TITLE
How to build a new plugin - template

### ISSUE THREAD

**Issue by mach37** [smartstoreag/SmartStoreNET#685]
Can you please provide some info in English so I can build my own plugin.

I love this over Nop Commerce!!! this is way better, I love the auto-update feature, now lets see if nop tries and copies SmartStore hahahhaaaa

Friendlier licensing

**Comment by mgesing** [comment]
I would take a look at an existing [plugin](https://github.com/smartstoreag/SmartStoreNET/tree/2.x/src/Plugins) and find one that best matches my needs. Then I would copy the plugin, change the ProjectGuid of the project file, rename files, names, namespaces and so on and finally I would replace functional code by my own code.

**Comment by net4u** [comment]
Maybe more useful a generic empty plugin (and if related to payments minimal dependencies to related model(s) and controllers)

**Comment by mach37** [comment]
hey any progress on building plugins and skinning easier?

**Comment by Michael-Herzog** [comment]
Duplicate of https://github.com/smartstoreag/SmartStoreNET/issues/822
