### ISSUE TITLE
Got 404 error when access to the admin page with last commit

### ISSUE THREAD

**Issue by riverstore** [smartstoreag/SmartStoreNET#688]
Hi! I've just downloaded last commit. After installed sucessfully, when access to admin I got 404 error message (accessing to other pages is fine)

Regard.

**Comment by hbopuri** [comment]
I have the same problem does any one addressed this issue?

**Comment by hbopuri** [comment]
Some progress: on my local site/bin it has SmartStore.Admin.* dll, config and pdb, SmartStore.Licensing.dll , Microsoft.Practices.ServiceLocation.dll, AutoMapper.Net4.dll  which were not copied over to my server when deployed. After copying those over manually, I tried to access admin now I get 
"A public action method 'TopicBlock' was not found on controller 'SmartStore.Admin.Controllers.TopicController'."

it looks like it is trying to access render web/view/Home/index.cshtml but searching for that method in admin TopicController.cs

**Comment by hbopuri** [comment]
Fixed: along with the above stuff, I deployed Admin site to server as site/Administration and all is now workgin

**Comment by suleymanpetek** [comment]
hi, i have the same problem, i could not solve as you, any ideas ?

**Comment by prazak** [comment]
Old Issue, but rebuilding of the solution after clone from GIT, solved it for me.

**Comment by nrsiddiqui** [comment]
I am facing same issue ... can any one ... please help .... what should i do .... admin page not coming ...  please provide urgent ....
