### ISSUE TITLE
Product quantity not added to cart on mobile theme

### ISSUE THREAD

**Issue by muratcakir** [smartstoreag/SmartStoreNET#691]
The amount always is 1.

**Comment by mgesing** [comment]
[Forum](http://community.smartstore.com/index.php?/topic/47008-bug-product-quantity-not-added-to-cart-on-mobile-theme/): "FYI: This was a simple fix in the Product controller (I think - don't have the code in front of me).  The form key string just needed to be tweaked to include ".AddToCart"."
