### ISSUE TITLE
Product variant attribute in product page should not be preselected implicitly

### ISSUE THREAD

**Issue by muratcakir** [smartstoreag/SmartStoreNET#694]
When the merchant does not mark any attribute option as pre-selected, then it's obvious that the buyer should be _enforced_ to select one by himself. But when we implicitly preselect the first option in the controller code, the buyer _could_ forget to make a proper selection and therefore possibly add a wrong variant to his cart.

**Comment by mgesing** [comment]
The merchant controls value preselection through the IsRequired option on attribute level (not through the pre-selection option on attribute value level).
