### ISSUE TITLE
Implement new export framework

### ISSUE THREAD

**Issue by muratcakir** [smartstoreag/SmartStoreNET#701]
Features:

* Supports products, orders and customers (and later maybe newsletters, news, blogs, forum etc.)
* Support for (persistant) export profiles
* Definition of data filters (categories, manufacturers, dates, tags, price ranges, product types, order states etc.)
* Data chunks (limit, offset, package/file size)
* Let the actual export be performed by specific providers which get invoked by framework
* Provider specific properties/configuration
* Publish files: Email, FTP, HTTP
* Background schedule processing of export profiles
* Refactor all current feed plugins to incorporate the new framework

**Comment by mgesing** [comment]
Resolved
