### ISSUE TITLE
Currencies: Multi-store selection cannot be saved

### ISSUE THREAD

**Issue by muratcakir** [smartstoreag/SmartStoreNET#703]
Furthermore: the _Save_ button should redirect to the currency list, but it doesn't, it behaves like the _Save & Continue_ button.

**Comment by mgesing** [comment]
Make primary exchange rate currency suitable for multi-stores too.

**Comment by mgesing** [comment]
Cannot reproduce. Anyway, found [another bug](https://github.com/smartstoreag/SmartStoreNET/commit/e27de70196cb4e24fbcdb51c93e2eb73e8fd3eef) while testing.
