### ISSUE TITLE
Import skip column with empty value

### ISSUE THREAD

**Issue by thomas-tran** [smartstoreag/SmartStoreNET#712]
The import function did not work for row with empty column value
For example 
ProductID, ProductName, CategoryName
1, Product A,
1, Product B,

Instead of import CategoryName as null value, it throw exception on key value in not in dictionary

**Comment by Michael-Herzog** [comment]
I can't reproduce this error. Please tell me which version of SmartStore.NET you're using. A sample file would be great too. If you can provide one so I can reproduce this problem I will reopen this issue.
