### ISSUE TITLE
The type or namespace name 'Licensing' does not exist in the namespace 'SmartStore'

### ISSUE THREAD

**Issue by suraj13** [smartstoreag/SmartStoreNET#714]
Hi,

I just downloaded SmartStoreNet application. I am able to build and run Front end part. But Back end part is not building. It is giving following error:

"The type or namespace name 'Licensing' does not exist in the namespace 'SmartStore'". 

I have added reference to Admin project, still it is giving same error. Please see screenshot.

Please help. thanks in advance.
![smartshopnet](https://cloud.githubusercontent.com/assets/5890655/8251012/6ee1b53e-1696-11e5-8437-5f7aa02a49ac.PNG)

**Comment by mgesing** [comment]
Try to solve it by replacing SmartStore.Licensing.dll with the [current one](https://github.com/smartstoreag/SmartStoreNET/blob/2.x/lib/SmartStore.Licensing/SmartStore.Licensing.dll).
