### ISSUE TITLE
Google Merchant Center plugin

### ISSUE THREAD

**Issue by drtikol** [smartstoreag/SmartStoreNET#716]
Not work correctly with SQL CE. SQL CE not support OVER an ROW_NUMBER function

**Comment by mgesing** [comment]
The entity framework does not support to share context instances across repositories and therefore generic SQL is required here. See no way to accomplish that with CE supported syntax.

**Comment by drtikol** [comment]
SQL CE 4 (SQL 2012] support OFFSET {0} ROWS FETCH NEXT {1} ROWS ONLY. I am used other SQL query to get total count with where clause.

**Comment by mgesing** [comment]
I will have a look on it.

**Comment by drtikol** [comment]
Note: subquery as t3 not necessary. OFFSET work on SQL Server 2012 above.

**Comment by mgesing** [comment]
[Updated](https://github.com/smartstoreag/SmartStoreNET/commit/be90cf52fd3fa4cf785b3ed946359915f17996b3)... it's working but not a very nice solution. It feels like a workaround for a insufficiency of a database product.
