### ISSUE TITLE
Refactor performance bottleneck in PriceCalculationService.GetLowestPrice()

### ISSUE THREAD

**Issue by muratcakir** [smartstoreag/SmartStoreNET#734]
It gets called too many times during product list rendering, _at least_ 1x per item. This results in too many database calls, because `ProductVariantAttributes` and `ProductVariantAttributeValues` are lazy navigation properties.

Consider minimizing database calls to a minimum, preferrably loading all potentially required records in one go.

**Comment by mgesing** [comment]
Resolved.
