### ISSUE TITLE
Would it be possible to trim whitespace from most if not all user entered data? 

### ISSUE THREAD

**Issue by nahjil567** [smartstoreag/SmartStoreNET#744]
We are running into an issue with Paypal address validation where if a person types a space before/after their address, or city Paypal says no can do. I'm not sure how difficult this would be to fix but would be very nice to have in the future, especially for mobile users as a tap on the City name results in an added space at the end.

**Comment by Michael-Herzog** [comment]
Hi,

I just tried to reproduce this problem with the PayPal Standard method but I couldn't. Which of the PayPal methods are you reffering to?

Regards

**Comment by nahjil567** [comment]
Well it is Standard, and I this is the an example address
118 Deerwalk Circle
Marietta , OH 47570
All I did to it was remove the space that was after Marietta and it was accepted by Paypal.

**Comment by Michael-Herzog** [comment]
I can't reproduce this behaviour with your data. Can you reproduce it by putting the space back in? If you can please make a screenshot.

**Comment by nahjil567** [comment]
![paypal error](https://cloud.githubusercontent.com/assets/4767192/9009095/6cef670a-3764-11e5-925b-3f892f5ef8c6.PNG)
![shipping](https://cloud.githubusercontent.com/assets/4767192/9009100/757f33dc-3764-11e5-9076-38a385ef7555.PNG)
![capture](https://cloud.githubusercontent.com/assets/4767192/9009101/77013fe8-3764-11e5-964f-ed0416288134.PNG)

**Comment by Michael-Herzog** [comment]
I still cannot reproduce this problem :-( I've tried every possibility to enter a address (checkout, customer account, backend) and have enetered  dozens of whitspaces. Which version of SmartStore.NET are your using?

**Comment by nahjil567** [comment]
2.2.1.0 It may be due to a setting we have in PayPal. We are requiring people to ship to the address they enter into our site. I'm not sure. It doesn't happen a ton, but the few times it does it is traced back to either a misspelled word or white space somewhere.

**Comment by Michael-Herzog** [comment]
Since there are no other complaints about this issue and I cannot reproduce it, I won't amend the code. But you could do it yourself:

Plugins > SmartStore.PayPal > PayPalStandardProvider > PostProcessPayment > line 259
