### ISSUE TITLE
Error when clicked on "clear list" button inside "compare products" on top menu

### ISSUE THREAD

**Issue by divsoft** [smartstoreag/SmartStoreNET#751]
URL : http://localhost/compareproducts

![Image](https://cloud.githubusercontent.com/assets/8091773/9208695/63abf646-4091-11e5-824f-4e70bfac9865.PNG)

Compiler Error Message: CS1061: 'SmartStore.Web.Models.Catalog.ProductOverviewModel' does not contain a definition for 'FullDescription' and no extension method 'FullDescription' accepting a first argument of type 'SmartStore.Web.Models.Catalog.ProductOverviewModel' could be found (are you missing a using directive or an assembly reference?)

Source Error:

Line 136:                            {
Line 137:                                <td style="width: @columnWidth;" class="a-left">
Line 138:                                    @Html.Raw(product.FullDescription)
Line 139:                                </td>
Line 140:                            }

Source File: c:\SRC\Views\Catalog\CompareProducts.cshtml    Line: 138

**Comment by mgesing** [comment]
Resolved. Thank you for reporting.
