### ISSUE TITLE
Primary Store Currency help text typo(s)

### ISSUE THREAD

**Issue by davza** [smartstoreag/SmartStoreNET#761]
In the latest source (2.x branch) There are two new fields in the Currency Details screen: /Admin/Currency/Edit/1
"Is primary store currency for" and "Is exchange rate currency for", in both of these tool tips "stores" is spelled "shores"

![2015-08-23 22_26_00-start](https://cloud.githubusercontent.com/assets/8984353/9430050/b1958616-49e6-11e5-973f-443392d833cd.png)

**Comment by Michael-Herzog** [comment]
Thanks for reporting
