### ISSUE TITLE
Payment Method description Typo(s)

### ISSUE THREAD

**Issue by davza** [smartstoreag/SmartStoreNET#764]
There are typos on the "Cash on delivery" and "Prepayment" payment methods.
"Once your order is placed, you will be contacted by our stuff to confirm the order."
stuff --> staff

![payment methods _ smartstore net](https://cloud.githubusercontent.com/assets/8984353/9478410/10b6c01e-4b78-11e5-990f-c33ee2f6c973.png)

**Comment by Michael-Herzog** [comment]
The typos for Cash on delivery and Prepayment were already corrected. I found the typo still in the Incoice payment method (and corrected it). Thanks for reporting!
