### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by tynar** [smartstoreag/SmartStoreNET#774]
I cannot figure out how to install the store. What I've done so far.
1. git clone the project
2. set AutomaticMigrationsEnabled = true in MigrationsConfiguration.cs
3. Run (hit F5)
4. Check 'Create Sample Data'
5. Select 'Use SQL Server (or SQL Express) database [Recommended]'
6. Provide SQL Server settings
7. Check 'Create database if it doesn't exist'
8. Hit Install button

The error is :
Setup failed: Column names in each table must be unique. Column name 'RowVersion' in table 'dbo.ScheduleTask' is specified more than once.

During installation process I see that database is created, but after error occurs database is dropped.

I'm using VS2013 and SQL Server 2012.

Can someone help me?

**Comment by mgesing** [comment]
Could you please
- git-pull again
- do not set DbMigrationsConfiguration.AutomaticMigrationsEnabled to true
- install again
