### ISSUE TITLE
Deleting attributes without recreating attribute combinations could result in wrong stock handling

### ISSUE THREAD

**Issue by mgesing** [smartstoreag/SmartStoreNET#785]
Thus irregular ProductVariantAttributeCombination.AttributesXml remains in the database.

**Comment by adameldaba** [comment]
When you go to any product and add Product Attribute Combination through clicking "Create All Combinations" it deletes all combinations on the table. Have you experienced the same issue?

**Comment by mgesing** [comment]
Unfortunately, yes. That's an evil bug. [Fixed it](https://github.com/smartstoreag/SmartStoreNET/commit/a16fd015d13ca510f9cf00c1a59fcd34affff82d). Thank you for reporting.

**Comment by adameldaba** [comment]
Thank you for the quick response. We would love to be contributors on this
project, what's the process?

Adam Eldaba  | Founder

Softmills  | www.softmills.com
We Harvest Innovations
C: 1.647.895.6423 | C: 971.55.947.3444 *|* E: adaba@softmills.com
<mshahin@softmills.com>
North America Office:
Unit 24, 2123 Walker's Line
Burlington, ON
Canada L7M 4Z9 Middle East Office:
7 Bin Khatheir st.
Heliopolis, Cairo
Egypt

Confidentiality Warning:
This e-mail contains information intended only for the use of the personnel
of Softmills. If the reader of this e-mail is not the intended recipient or
the employee or agent responsible for delivering it to the intended
recipient, any dissemination, publication or copying of this e-mail is
strictly prohibited. The sender does not accept any responsibility for any
loss, Disruption or damage to your data or computer system that may occur
while using data contained in, or transmitted with, this e-mail. If you
have received this e-mail in error, please immediately notify us by return
e-mail. Thank you.

**Comment by mgesing** [comment]
We prepared a page of [how to contribute](http://docs.smartstore.com/display/SMNET/How+to+contribute). If you want to contribute code then please use [pull requests](https://github.com/smartstoreag/SmartStoreNET/pulls).

**Comment by mgesing** [comment]
Cannot reproduce. AreProductAttributesEqual cannot return true in such a case.
