### ISSUE TITLE
IIS Admin configuration issue

### ISSUE THREAD

**Issue by raj-doshi** [smartstoreag/SmartStoreNET#786]
Hi,

As I downloaded source code of SmartStoreNET and configured it in to IIS and then click myurl/admin not working. I found that admin project is not included in Web project so I configured it by adding virtual directory named "admin" gave path of admin project then also its not working. Please anyone have solution provide me. Thanks in advance.

**Comment by liuhaifancy** [comment]
so am I,but use debug can load admin page,why?
