### ISSUE TITLE
Store Crashes on its own Often

### ISSUE THREAD

**Issue by qanuj** [smartstoreag/SmartStoreNET#789]
SmartStore would keep running for a while and then it crashes without any changes in code or deployment. with error

`Could not load type 'System.Data.Entity.Infrastructure.TableExistenceChecker' from assembly 'EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.`

![ss-crash](https://cloud.githubusercontent.com/assets/244855/10215717/9248641c-6841-11e5-8ae7-fe49bf125ec6.PNG)

Any specific deployment or installation checks to be done ?

**Comment by qanuj** [comment]
Closed without any information ? how come ?

**Comment by muratcakir** [comment]
Sorry, but it's absolutely unreproducable.
