### ISSUE TITLE
"CREATE ALL COMBINATIONS" & "DELETE ALL COMBINATIONS" under the product page and attribute tab has a major issue

### ISSUE THREAD

**Issue by adameldaba** [smartstoreag/SmartStoreNET#793]
ISSUE: When clicking on either of the buttons, all attribute combinations FOR ALL PRODUCTS (not only the one you are editing) are deleted from the database completely (table: ProductVariantAttributeCombination).

Cause of Issue: When either of those buttons are clicked, "DeleteAll()" method from the IRepository is called without any parameters or filters. With no filters passed in the parameter, the method deletes all the rows from the specified table.  

Work Around: If you go ahead and add combinations individually, one by one, by clicking on "+Add Combination", the code inserts a record into the table without deleting records from the table. For people with a lot of combinations, this is a time consuming process.

SOLUTIONG: Add the following parameter:
x => product.Id == x.ProductId
to the "DeleteAll()" call at the following methods in the SmartStore.Admin.Controllers.ProductController
* public ActionResult DeleteAllAttributeCombinations(ProductVariantAttributeCombinationModel model, int productId)
*public ActionResult CreateAllAttributeCombinations(ProductVariantAttributeCombinationModel model, int productId)

Should look like this: _pvacRepository.DeleteAll(x => product.Id == x.ProductId);

**Comment by mgesing** [comment]
[Resolved](https://github.com/smartstoreag/SmartStoreNET/commit/a16fd015d13ca510f9cf00c1a59fcd34affff82d). Thank you for reporting.
