### ISSUE TITLE
Limitation on Currency with Multi-store sites

### ISSUE THREAD

**Issue by adameldaba** [smartstoreag/SmartStoreNET#799]
We are facing the same issue.  We have multiple stores in different countries using different currencies.  As per the configurations today, we have inserted all our products using AED as the primary currency as the first store is in the UAE.  Now all pricing are AED as primary. Lets call this store UAE_Store

Now I just opened a second store in Egypt which uses EGP as its currency. Lets call this store EGP_Store.

When I select the primary currency as EGP for EGP_Store and select the exchange currency as AED (because all my pricing is based on this currency), and save; when I go to the store EGP_Store, the currency displayed is correct, but the value is incorrect, because it does not exchange the value. It only exchanges the value if I manually select another currency from the top right which is incorrect.  

I don't want the user to keep changing currency, I want depending on which store they enter, the correct currency and the value is displayed to the user.  

A quick fix could be to add a new field: "DisplayCurrency" and that way for each store we can choose the default currency to be displayed.  If it is not the same as the "Primary Currency" then it's value should be equated to the exchange rate and displayed correctly in the store. This way I can use all the products I currently have and not need to insert them in every country.

**Comment by mgesing** [comment]
The primary store currency and the primary exchange rate currency will be suitable for multi-store in SmartStore.NET 2.5. #704

**Comment by adameldaba** [comment]
Thank you for the prompt response. Do you have any idea of the date this
release will happen?

Best Regards


Adam Eldaba  | Founder

Softmills  | www.softmills.com
We Harvest Innovations
C: 1.647.895.6423 | C: 971.55.947.3444 *|* E: adaba@softmills.com
<mshahin@softmills.com>
North America Office:
Unit 24, 2123 Walker's Line
Burlington, ON
Canada L7M 4Z9 Middle East Office:
7 Bin Khatheir st.
Heliopolis, Cairo
Egypt

Confidentiality Warning:
This e-mail contains information intended only for the use of the personnel
of Softmills. If the reader of this e-mail is not the intended recipient or
the employee or agent responsible for delivering it to the intended
recipient, any dissemination, publication or copying of this e-mail is
strictly prohibited. The sender does not accept any responsibility for any
loss, Disruption or damage to your data or computer system that may occur
while using data contained in, or transmitted with, this e-mail. If you
have received this e-mail in error, please immediately notify us by return
e-mail. Thank you.

**Comment by mgesing** [comment]
No, not exactly. Maybe at the end of the year.
