### ISSUE TITLE
SmartStore.Licensing.dll is showing corrupted

### ISSUE THREAD

**Issue by pradudev** [smartstoreag/SmartStoreNET#810]
After cloning master branch and I tried to build the solution in VS 2015.
I was getting below error F:\Coding\CMS\SmartStoreNET\lib\SmartStore.Licensing\SmartStore.Licensing.dll' could not be opened -- Illegal tables in compressed metadata stream.

I tried to inspect this dll using ILSpy, over there also the dll showed corrupted.

**Comment by mgesing** [comment]
See [#714](https://github.com/smartstoreag/SmartStoreNET/issues/714) and [#749](https://github.com/smartstoreag/SmartStoreNET/issues/749).
