### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by astepanian1** [smartstoreag/SmartStoreNET#812]
Hi guys hope you can advice I just build and deployed project to local IIS and I am running a SQL 2012 standard edition when i launch website as directed in manual i get following error:

The argument 'nameOrConnectionString' cannot be null, empty or contain only white space.

How to get this to work with non express SQL where should i make the changes in code? Is there script that expects Express edition and when doesnt find it trows that error?

**Comment by bettimms** [comment]
If you are running it locally try as connection string localdb, simply to connection string input write " . " (without " ", just dot -> .
The . character will map to local db.

**Comment by astepanian1** [comment]
Thank you for quick reply
