### ISSUE TITLE
Unable to find payment gateway/merchant account settings

### ISSUE THREAD

**Issue by astepanian1** [smartstoreag/SmartStoreNET#814]
Guys, is there a place where I can specify the payment gateway/merchant account for credit card processing I am thinking for instance to use Authorize.Net. I was unable to find it on administration panel?

Much appreciated,

Alex

**Comment by Michael-Herzog** [comment]
You can find a plugin for Authorize in our marketplace:
http://community.smartstore.com/index.php?/files/file/30-authorizenet-payment/
