### ISSUE TITLE
Timezone mismatch in AJAX grids

### ISSUE THREAD

**Issue by davza** [smartstoreag/SmartStoreNET#819]
There seems to be a problem with the UTC times on the scheduled tasks.
See screen below.
Specifically the "Send Emails" task. It should be triggered every minute, but will only fire again two hours after the last one.

The time on my local PC is: 23:28, I think the server uses UTC/GMT (21:26).
On the web page it says the Last Run was 23:26 and the next run 01:27 (two hours and a minute later.
The LastRun time is correct in my local time.

In the database, the LastStartUtc, LastEndUtc, LastSuccessUtc all look right, but the "NextRunUtc" seems to be in my local time, not Utc.

The times work fine with the database and application all on my local network (the mails are processed minutely as expected)

![image](https://cloud.githubusercontent.com/assets/8984353/11381259/b78bcbbe-9303-11e5-9189-e0266829cfc9.png)

**Comment by davza** [comment]
There is also a timezone problem on the ActivityLog Screen. (and possibly most that use the Html.Telerik().Grid control)

It looks like the grid always wants to convert to the browsers local time if the timezone is different between the Server and Client, if the timezones are the same, then it does not convert it. (when I run the server from my local machine all times are stored and displayed correctly)

I added extra debugging info to the Activity log Message when the time is converted or user time for display on the grid.
The details are:
Time stored in DB (Utc): 2015-11-29 09:19:07.307
Time used on server to convert to local time: 09:19:07 AM
Converted Time on server: 11:19:07 AM
Time Displayed in Grid: 01:19:07 PM
Time on PC: 11:19:00 AM

All the times above are correct, except the one displayed on the grid.
The "time on server" mentioned above is in ActivityLogController.ListLogs


![image](https://cloud.githubusercontent.com/assets/8984353/11456257/5bdffaf6-968c-11e5-94a8-cd8296818050.png)

I think this is related to the issue on the Scheduled Tasks screen, but there might be more to the Scheduled tasks problems.

**Comment by davza** [comment]
Hi, I've been looking at the dates a bit, I know it is a massive job, but if we had the option, would it be a good idea to use DateTimeOffset for all the date objects in the .net classes and have the date display formatting done in the razor pages?

I added an extra CreatedOnOffset (DateTimeOffset) to the ActivitlyLog Model and correct time displayed in the grid, but it still needs to be formatted nicely.
I think this is because the Telerik Grid does not apply any formatting to the DateTimeOffset data type.

![image](https://cloud.githubusercontent.com/assets/8984353/11457400/5fbcb6ae-96b0-11e5-8510-5ad66989aee4.png)

**Comment by muratcakir** [comment]
Did you set the correct time zone in **Configuration > Settings > Customer settings > DateTime settings**?

**Comment by davza** [comment]
Yes,
Customers are not allowed to select the time zone.
The Default Store time zone is UTC+2, Harare, Pretoria

![image](https://cloud.githubusercontent.com/assets/8984353/11523093/8d3c4a68-98c7-11e5-9812-8a2380cbbd3d.png)

**Comment by muratcakir** [comment]
I can confirm this to be a Telerik Grid _glitch_. When rendering per AJAX, it assumes that date fields are of UTC kind and adds the local/browser time offset to them. But we already convert dates to the user-defined timezone already *on the server side* (the user-defined timezone is the one configured in **Configuration > Settings > Customer settings > DateTime settings**).

Two possible solutions:
* Feed the grid with UTC-dates only (don't convert on server)
* Use string model properties instead of original DateTime.

The first ist problematic, as we often use the very same fields outside of AJAX scenarios. The latter works on both server and clide side, but requires a lot of refactoring.

*DateTimeOffset* requires even more work.

Let me think about it...

**Comment by davza** [comment]
Thanks, 7b398b1c06177d81add580d3efe12d43caa4fd90 fixes the problem with the mail scheduler (and other scheduled tasks) only being re-queued at the interval +2hours.

Let me know what your thoughts are around the date-time conversions, I might be able to help.
my feel is that the first option would be the better option. So the server only deals with UTC and anywhere the dates are shown to a user they are converted to the correct time-zone and "culture specific" display formatting. 
This would ether happen automatically on the grid as it currently is, or via display helper functions.

**Comment by muratcakir** [comment]
Solved the issue by converting dates back to *UTC* kind, when they are *Unspecified*. This only happens when the action's result type is *JsonResult* (because the issue comes up only in AJAX scenarios). In order to be able to intervene in the serialization process, I had to incorporate *Json.NET*. The new *JsonNetAttribute* action filter now handles the serialization (which is a very positive side effect, because Json.NET is much faster than the built-in *JavascriptSerializer*).

**Comment by davza** [comment]
Hi, This doesn't seem to solve the problem with the AJAX grids.

When I found the problem and was testing it, I tried setting the DateTimeKind to UTC, local andd the servers time-zone, but the problem looked like that the Grid always assumes that the dates/time coming back for the server will be in the same timezone (or UTC time) if the the server is in a different timezone to the client (browser). and does not look at the DateTimeKind property of the date (I don't think this property is passed to the client)

Looking at the JSON that is returned to the client, there is only a single value for Date, no indication of time-zones, but I might be missing something 
{"ActivityLogTypeName":"Edit category",
"CustomerId":1,
"CustomerEmail":"mark@home.com",
"Comment":"Edited a category ('Homeware')",
"CreatedOn":new Date(1449599797017),
"Id":23270,
"CustomProperties":{}}

**Comment by muratcakir** [comment]
There is no *DataTimeKind* or something similar on the client side. Just a date.

What exactly goes wrong with dates in AJAX grids after the fix?

**Comment by davza** [comment]
It still has the same behavior as before. The time is still converted from the time sent from the server, to the time on the client.

Yes, I know that the DateTimeKind property is a .net thing and not available in JS, what I was trying to say there is:
When I looked at it, before adding an extra field of type DateTimeOffset to the ActivityLogModel and grid, I first tried setting the DateTimeKind property of the CreateOn field and no matter what I set it to, the client (grid) would always treat it as the same date that was coming back from the server, the DateTimeKind property was ignored.


Now it looks like when the date is serialized on the server, it only converts the actual DateTime to the timestamp [Date(1449599797017)], it does not take the time-zone into account, so setting the DateTimeKind property on the server has no affect as to the time that is displayed in the grid.

**Comment by davza** [comment]
Attached is a screenshot of the current code running on the server.

The Date and Time is right on the Order Details page (or any of the details pages), but on the grid it still assumes that the Date/Time coming from the server is UTC and converts to to the clients (browsers) Timezone.

![image](https://cloud.githubusercontent.com/assets/8984353/11685052/d918bd56-9e7e-11e5-9055-382ea63f9220.png)

**Comment by muratcakir** [comment]
That's by design. I wrote a pretty large comment when fixing the issue. Here it is:

```c#
public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
{
	if (value is DateTime)
	{
		var d = (DateTime)value;
		if (d.Kind == DateTimeKind.Unspecified)
		{
			// when DateTime kind is "Unspecified", it was very likely converted from UTC to 
			// SERVER*s preferred local time before (with DateTimeHelper.ConvertToUserTime()).
			// While this works fine during server-time rendering, it can lead to wrong UTC offsets
			// on the client (e.g. in AJAX mode Grids, where rendering is performed locally with JSON data).
			// The issue occurs when the client's time zone is not the same as "CurrentTimeZone" (configured in the backend).
			// To fix it, we have to convert the date back to UTC kind, but with the SERVER PREFERRED TIMEZONE
			// in order to calculate with the correct UTC offset. Then it's up to the client to display the date
			// in the CLIENT's time zone. Which is not perfect of course, because the same date would be displayed in the 
			// "CurrentTimeZone" if rendered on server.
			// But: it fixes the issue and is way better than converting all AJAXable dates to strings on the server.
			value = _dateTimeHelper.ConvertToUtcTime(d, _dateTimeHelper.CurrentTimeZone);
		}	
	}

	_innerConverter.WriteJson(writer, value, serializer);
}
```

Converting all dates to strings would correctly show the server date on the client, but refactoring this is a no-go at this moment. So for now we have to live with this glitch.

**Comment by davza** [comment]
Hi, thanks for looking into this.
Just to let you know, this has sorted out the problems that I was having with the timezones between the client and the server.
