### ISSUE TITLE
Product detail image size setting is not applied in front-end

### ISSUE THREAD

**Issue by iherwald** [smartstoreag/SmartStoreNET#826]
To reproduce the behaviour:
Modify 'Product detail image size' in back-end media settings (e.G. from 300 to 600). 
Than open a product detail page in front-end.

The product detail image 'flashes' in the correct size (600) and than immediately falls back to the previous size (300).

**Comment by muratcakir** [comment]
It's because the viewport height is limited to 300 px. I admit, this is not really smart. I'm on it.
