### ISSUE TITLE
Guest shopping cart is "shared" for whole IP Address

### ISSUE THREAD

**Issue by davza** [smartstoreag/SmartStoreNET#828]
When browsing the store as a guest, the guest shopping cart is shared for all the users coming from the same IP address.
This will cause problems when multiple people at the same location are shopping.

This is happening on the latest 2.x branch.
This is not happening on the demo site, so it could be something that was introduced.
I remember reading a previous issue relating to creating fewer guest account for search engines, #773 which could have this side effect.

This example uses 3 browsers on a single PC, Firefox, Chome, Chrome Private.
You would expect all to have separate guest accounts.
I also tested from another PC on the same network and a cellphone and confirm that all shared the same guest shopping cart.

![image](https://cloud.githubusercontent.com/assets/8984353/11546099/d1670034-9953-11e5-9829-ddc17acf2b9e.png)

**Comment by muratcakir** [comment]
@mgesing Find a better strategy or - if not possible - revert changes.

**Comment by davza** [comment]
Thanks, this is working fine now.
