### ISSUE TITLE
Improve default menu

### ISSUE THREAD

**Issue by andriisydor** [smartstoreag/SmartStoreNET#830]
Menu is outdated and makes worse impression.
as good example:
https://www.victoriassecret.com/
http://www.nike.com/us/en_us/
![best practice](http://i.imgur.com/BR9PF3B.png)

maybe is good to make it 3 levels or start droppable as current from 3+ lvls
add ability to add icon for menu item

**Comment by muratcakir** [comment]
Already scheduled for V3 (2016 Q3). But bear in mind that - from experience - automatically created megamenus never look THAT good, because you never know how many content there is to be processed.

**Comment by Michael-Herzog** [comment]
MegaMenu plugin creates better results then both named examples ;-)
