### ISSUE TITLE
Unable to execute the project from VS 2013

### ISSUE THREAD

**Issue by sk987** [smartstoreag/SmartStoreNET#837]
Hi,

I have downloaded the project from github, I ran the project and it has gone to the installation mode, and provide all the necessary information to setup. The db has been created successfully(when i checked on sql server). But it is giving a following error.

{"During translation of LESS-code, readed from the file '/Themes/Alpha/Content/theme.less', to CSS-code error has occurred.\r\nSee more details:\r\n\r\nObject doesn't support this property or method"}

{"Object doesn't support this property or method"}

**Comment by muratcakir** [comment]
Dup of #324
