### ISSUE TITLE
All Task never RUN always show "Waiting..."

### ISSUE THREAD

**Issue by afandylamusu** [smartstoreag/SmartStoreNET#842]
![issue_842_tasksscheduler](https://cloud.githubusercontent.com/assets/6712144/12018251/771ddf1c-ad58-11e5-9689-adab46c85d80.PNG)
Hi Team,

I tried to running SmartStoreNET 2.x in AWS t2.micro but all task is never RUN, "Next Run in" column always show "Waiting...".

Please help me to fix this issue.

Thanks,

Kindly Regards,

Afandy

**Comment by muratcakir** [comment]
The base URL called to execute the scheduled tasks is being resolved automatically on app startup (it is either your first store's URL, or - if the store URL is not valid - the request base URL). Maybe this URL is invalid in your environment. You can however explicitly set the task scheduler base URL in **web.config**.

```xml
<!-- uncomment and set this to your store's task scheduler base url when the automatic url resolution fails (e.g. 'http://www.mystore.com/taskscheduler') -->
<!--
<add key="sm:TaskSchedulerBaseUrl" value="" />
-->
```

Please follow the instruction in the comment, try again, and give us feedback about whether it worked.

**Comment by afandylamusu** [comment]
I have follow that setting to change the sm:TaskSchedulerBaseUrl. But when I change the Store URL and domain to be same. Its works for me now.

Thanks :)
