### ISSUE TITLE
Design Issue

### ISSUE THREAD

**Issue by rkumar670** [smartstoreag/SmartStoreNET#849]
I just download the Smartstore, and complied successfully but after running the application the UI is not coming like demo...css are not loading same as the demo.. may you please help me,

Thanks,
Rahul

**Comment by rkumar670** [comment]
![capture](https://cloud.githubusercontent.com/assets/1597317/12534960/53c440f8-c296-11e5-8406-4cc9dd83ba4f.PNG)

**Comment by rkumar670** [comment]
i think .less file are not working could you please help me.

Thanks,

**Comment by mgesing** [comment]
Open the developer console in Chrome (by pressing F12) and look for errors in the network tab. Click on one to get details about the problem.

**Comment by rkumar670** [comment]
Hi Mgesing,
Thanks for your reply.

following message is coming while refreshing the page..

![image](https://cloud.githubusercontent.com/assets/1597317/12558219/8a0143ae-c3b4-11e5-9d9c-067ac1c495b8.png)

Please help

**Comment by mgesing** [comment]
Please look for network errors in the network tab and click on one to get details.

**Comment by rkumar670** [comment]
not found any error..
![Uploading image.png…]()

**Comment by rkumar670** [comment]
not found any error
![image](https://cloud.githubusercontent.com/assets/1597317/12559868/7f349b8e-c3bd-11e5-913b-62efdd1cb204.png)

**Comment by rkumar670** [comment]
@mgesing please help me...it is not resolved, .less file is not rendering...
Thanks,

**Comment by mgesing** [comment]
Ensure that "Static Content" is enabled in IIS Windows Features as described [here](http://stackoverflow.com/questions/6089070/resource-interpreted-as-stylesheet-but-transferred-with-mime-type-text-html-in-a/27256618#27256618).

**Comment by rkumar670** [comment]
but I am running the application in visual studio 2012 and iis setting are enabled as mentioned in link shared.

THANKS

**Comment by muratcakir** [comment]
Min. IDE requirement for SmartStore.NET is Visual Studio **2013**.

**Comment by rkumar670** [comment]
@muratcakir @mgesing  Thanks for the support , it is working perfect in VS 2015. :)
