### ISSUE TITLE
File Upload Error

### ISSUE THREAD

**Issue by Cbrown35** [smartstoreag/SmartStoreNET#858]
I am not able to upload anything larger than 50-175 MB. I have updated IIS as well as updated appConfig/WebConfig. 

<img width="960" alt="smartstore_upload_error_message" src="https://cloud.githubusercontent.com/assets/6312087/13420513/80bed0c8-df4c-11e5-82a1-a72369919363.png">
<img width="960" alt="smartstore_upload_error_message" src="https://cloud.githubusercontent.com/assets/6312087/13420522/91eb510a-df4c-11e5-9142-4ef873ecba07.png">

**Comment by mgesing** [comment]
[Large file upload - out of memory](http://community.smartstore.com/index.php?/topic/47596-large-file-upload-out-of-memory/)
