### ISSUE TITLE
Tax Reverse Engineering Calculation Issue

### ISSUE THREAD

**Issue by shuja-zaka-khan** [smartstoreag/SmartStoreNET#869]
Hi,

I am using Smart Store prices incl. of tax feature. There is a calculation issue in reverse engineering the tax.  See below:-
![your store shopping cart prices incl of tax rounding errors](https://cloud.githubusercontent.com/assets/2353729/13703657/558b80ca-e7b9-11e5-8891-5540334209e6.png)

**Comment by depmar** [comment]
The 7% of 93.46 is exactly$ 100.00

**Comment by shuja-zaka-khan** [comment]
Thanks mate !! I figured out the mistake I made in my calculation.
