### ISSUE TITLE
Topic HomePageText is SE indexed even if not included in sitemap

### ISSUE THREAD

**Issue by mgesing** [smartstoreag/SmartStoreNET#891]
It should not be indexed by search engines.

Furthermore `login?ReturnUrl=` and `register?ReturnUrl=` are indexed multiple times.

**Comment by muratcakir** [comment]
If option _RenderAsWidget_ is active, then routing to this topic will be disabled, preventing it to be indexed.

`Login` and `Register` are now SE disallowed, see commit 21e6071
