### ISSUE TITLE
Add brazilian portuguese translation

### ISSUE THREAD

**Issue by lucasven** [smartstoreag/SmartStoreNET#893]
Hi, what about add brazilian portuguese translation to this project?

i wish i could use this project, but i need this feature. 
I can implement it by myself and make a pull request.

**Comment by Michael-Herzog** [comment]
Hi,

Translations of textual resources are not part of the core project and therefore wont be pulled.
Please have a look at the bottom of the following link:

http://docs.asp-shopsystem.de/display/SMNET/Managing+Languages

Regards

**Comment by lucasven** [comment]
Thanks for the feedback, i'll create a language pack then.
