### ISSUE TITLE
Check Out as Guest Button not showing up

### ISSUE THREAD

**Issue by rzpatel** [smartstoreag/SmartStoreNET#896]
I have seen this happen intermittently. One way I have figured to reproduce this is if you start with an empty cart, add a product and select go to cart from the mini cart and it takes you to the login page as expected but the check out as guest button is missing. I have noticed the same behavior both on version 2.2 and 2.5. At times I have also seen the basket showing as empty at the login page but when you add another item to the basket, the previous item shows up.

**Comment by mgesing** [comment]
The "Go to cart" button takes you to the cart page without any redirect to the login page. The redirect happens when entering the checkout but then the "checkout as guest" button is displayed. It is not displayed when clicking "Log in" directly.

**Comment by rzpatel** [comment]
Okay it appears that this only happens when ssl is enabled.  When you come into the site as a guest and add in a product to the cart and click the checkout button in the mini shopping cart, it redirects you to the login page with no guest option. This only happens the first time you click the check out button. Upon subsequent clicks it does redirect with the correct guest option.

**Comment by Michael-Herzog** [comment]
I've tested in two shops (2.5.0) with SSL enabeled and cannot reproduce this behaviour.
If you can post a URL where I can reproduce this problem please open the issue anew.
