### ISSUE TITLE
how can I add a new field or table in SmartStore?

### ISSUE THREAD

**Issue by thomasaldwin** [smartstoreag/SmartStoreNET#897]
Hi, could you tell me how to add field or a table using code first in SmartStore.Net because i kinda confused like customer model were split into registermodel, login model, etc. I didn't get the idea how to add a new field there?

Thanks..

**Comment by mgesing** [comment]
See [Entity Framework Migrations](http://docs.smartstore.com/display/SMNET/Entity+Framework+Migrations). PS: Login- and register model are view models, not domain model (classes).
