### ISSUE TITLE
USPS Plugin 2.2

### ISSUE THREAD

**Issue by rzpatel** [smartstoreag/SmartStoreNET#898]
The plugin is not encoding the service returned from USPS properly.

e.g.
USPS Priority Mail 2-Day&lt;sup&gt;&#8482;&lt;/sup&gt; (0.00)
USPS First-Class Mail&lt;sup&gt;&#174;&lt;/sup&gt; Parcel (0.00)

Also when can we expect a version 2.5 for the plugin 

Thanks.

**Comment by Michael-Herzog** [comment]
Hi,

I've just updated the plugin in the marketplace, it also includes a fix for problem described above:
http://community.smartstore.com/index.php?/files/file/79-usps-shipping-plugin/

Regards

**Comment by rzpatel** [comment]
Thanks for the update. Not sure if you are aware that while using PayPal express shipping charges do not get calculated. I am assuming this is because the store does not have the customers shipping address as it lies with PayPal
Regards

Sent from my Windows Phone
________________________________
