### ISSUE TITLE
Restrict payment methods to certain shipping methods.

### ISSUE THREAD

**Issue by muratcakir** [smartstoreag/SmartStoreNET#94]
For example, no payment method "CashOnDelivery" for shipping method DHL Express.

> Migrated from CodePlex: [Issue #89](https://smartstore.codeplex.com/workitem/89) from [WolfgangSchmerge](https://www.codeplex.com/site/users/view/WolfgangSchmerge), on 9/20/2013 9:04:54 AM

**Comment by mgesing** [comment]
[Resolved](https://github.com/smartstoreag/SmartStoreNET/commit/7fa48e659fc1a8fd4001d3fd0cc8347ceccffd0d)
