### ISSUE TITLE
Multiple Issues to Improve Performance 

### ISSUE THREAD

**Issue by panky2sharma** [smartstoreag/SmartStoreNET#942]
Combine external CSS (6)
Combine external JavaScript (59)
MINIFY CSS & JS files
Enable gzip compression (1)
Leverage browser caching (77) on all css & js 
![capture](https://cloud.githubusercontent.com/assets/2860834/14924081/4fb45110-0e5e-11e6-9449-b4be033a8be6.JPG)

Use CDN
Specify image dimensions (6)

Remove unused CSS rules (83% CSS not used on home page)

**Comment by muratcakir** [comment]
If you test in release mode, you'll get other results. Because only in release mode, resources get combined and minified.
