### ISSUE TITLE
Shipping Method Restrictions

### ISSUE THREAD

**Issue by rzpatel** [smartstoreag/SmartStoreNET#958]
After upgrade to 2.5 the shipping Method restrictions is not longer available. UNder the shipping methods > restirictions tab, what is displayed is "There were no possibilities found to restrict shipping methods."

**Comment by mgesing** [comment]
The restrictions are available through a [plugin](http://community.smartstore.com/index.php?/files/file/88-filter-for-shipping-methods/).

**Comment by rzpatel** [comment]
Thanks for the update. Wish it was mentioned in the release notes as this upgrade breaks an existing store. Additionally have seen an issue with the Paypal plugin where the error returned is related to the protocol communication between Paypal and the site. It could be related to TLS 1.1 and 1.2 as Paypal was to make some changes with the security protocol at their end. Wil  have to do more testing to conform this.
