### ISSUE TITLE
shipping methods are displayed twice or three times

### ISSUE THREAD

**Issue by SalehGladius** [smartstoreag/SmartStoreNET#981]
a store uses both 'fixed rate shipping' and 'shipping by weight',

so in the checkout all shipping methods are displayed twice.

how can i specify shipping methods for each shipping rate computation methods?

**Comment by mgesing** [comment]
That's correct behaviour because each duplicate results in different shipping costs and the customer must be able to choose it. Technically spoken, the list does not show shipping methods but shipping rate computation method results.
