### ISSUE TITLE
Error while creating the database

### ISSUE THREAD

**Issue by ionuttamas** [smartstoreag/SmartStoreNET#989]
Trying up a fresh install on my PC, gives out the following error:

`Setup failed: An error occurred during installation. Stage: PopulateCustomersAndUsers (Value cannot be null. Parameter name: source)`

Error produced here: 
`this.GenericAttributeService.SaveAttribute(adminUser, SystemCustomerAttributeNames.FirstName, adminUser.Addresses.FirstOrDefault().FirstName);`

**Comment by msamirma** [comment]
this happens to me too.
just create new database and then download from here
https://github.com/smartstoreag/SmartStoreNET/releases
2.6.0

**Comment by mgesing** [comment]
I've downloaded release of 2.6.0 and installed it with using SQL Server and let the installation process create the database. Worked for me without any problems.
