### ISSUE TITLE
Bug or missconfiguration?

### ISSUE THREAD

**Issue by net4u** [smartstoreag/SmartStoreNET#991]
Hi
I am not sure that what is pictured above is a bug or I do a wrong configuration.
What I do:
I set Prices includes tax on off, I set Tax Display type as Including tax (and by consequence a 20% VAT is added to final display price),  I set an unit price of 1000, I set Additional shipping charge as 15.
![2016-07-07](https://cloud.githubusercontent.com/assets/255743/16647252/0c90364c-4437-11e6-8765-06d912fb210e.png)

**Comment by muratcakir** [comment]
The result is absolutely correct: 1.000 + 20% VAT = 1.200 (+ 15 shipping surcharge)

**Comment by net4u** [comment]
Of course that mathematics is ok. But if you see at the end of string is another "**plus shipping**" . This I wonder if is correct.
