### ISSUE TITLE
Missing Manufacturer Bug?

### ISSUE THREAD

**Issue by net4u** [smartstoreag/SmartStoreNET#992]
Hi,

I added several manufacturers, (e.g. Allview, Alcatel, ASUS).
Then when I create a product, some of manufacturers are visible (e.g. Allview), others not (e.g. Alcatel, ASUS). But if I associate products to Manufacturers, it works.
![2016-07-07 1](https://cloud.githubusercontent.com/assets/255743/16649693/c8d61a78-4442-11e6-8f8f-9117470a1402.png)
![2016-07-07 2](https://cloud.githubusercontent.com/assets/255743/16649696/cd326694-4442-11e6-922c-dbe056d881b1.png)

**Comment by net4u** [comment]
I noticed that even if I delete some manufacturers from database, they are gone e.g. from first page, but still available in product edit dropdown. Also the manufacturers that I add and not visible in dropdown are visible on front-page.
![2016-07-07 7](https://cloud.githubusercontent.com/assets/255743/16651401/6764ed14-444c-11e6-8400-7ae705ecdbad.png)
![2016-07-07 6](https://cloud.githubusercontent.com/assets/255743/16651403/6765dde6-444c-11e6-8d3f-47fce3292b77.png)
![2016-07-07 5](https://cloud.githubusercontent.com/assets/255743/16651402/6764ea12-444c-11e6-96e0-20cae2eb6ea0.png)
![2016-07-07 4](https://cloud.githubusercontent.com/assets/255743/16651404/676a4048-444c-11e6-98b3-0d85b423881f.png)

**Comment by net4u** [comment]
I found that it was a misbehave of Edge browser in what concerns cache.

**Comment by muratcakir** [comment]
Seems to be a memory caching issue
